#!/bin/bash

##
# Do apt-get update, upgrade, fix missing, install recommends, autoremove, autoclean.
##

apt-get update && apt-get upgrade -f --fix-missing --install-recommends && apt-get autoremove && apt-get autoclean
