#!/bin/bash
set -euf -o pipefail

##
# Run apt-get commands to uplift the system:
#
#   * update
#   * upgrade
#   * clean, autoclean, autoremove with purge
#
# The upgrade uses:
#
#   * -y yes to everything
#   * -f force changes
#   * --fix-missing
#   * --install-recommends
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

## Scrub before uplift
sudo apt-get autoclean
sudo apt-get --purge autoremove

## Uplift
sudo apt-get update
sudo apt-get upgrade -y -f --fix-missing --install-recommends

## Scrub after uplift
sudo apt-get autoclean
sudo apt-get --purge autoremove
