#!/bin/bash

##
# Do apt-get remove on old kernels and headers.
#
# Credit: http://marc.waeckerlin.org/computer/blog/remove_all_old_kernel_images_in_ubuntu
#
# This script remove all old images, but keeps the running one. 
#
# For your comfort and safety, please upgrade your system
# then reboot before you execute this command to make sure
# the latest kernel is installed and running successfully.
#
# If you get an error, make sure you are running the 
# current kernel version, i.e. upgrade then reboot.
##

sudo apt-get remove --purge 'linux-image-[0-9].*' linux-image-$(uname -r)+
sudo apt-get remove --purge 'linux-headers-[0-9].*' linux-headers-$(uname -r)+
