#!/bin/bash
#
# Run apt-get commands to uplift the system:
#
#   * update
#   * upgrade
#   * clean, autoclean, autoremove with purge
#
# The upgrade uses:
#
#   * -y yes to everything
#   * -f force changes
#   * --fix-missing
#   * --install-recommends
#
set -o nounset
set -o errexit
set -o pipefail

## Scrub before uplift
sudo apt-get autoclean
sudo apt-get --purge autoremove

## Uplift
sudo apt-get update
sudo apt-get upgrade -y -f --fix-missing --install-recommends

## Scrub after uplift
sudo apt-get autoclean
sudo apt-get --purge autoremove
