#!/bin/sh
set -euf -o pipefail

##
# Do apt-get remove on old kernel images and headers.
#
# Credit: http://marc.waeckerlin.org/computer/blog/remove_all_old_kernel_images_in_ubuntu
#
# This script removes all old kernels while keeping the running kernel.
#
# For your comfort and safety, please upgrade your system
# then reboot before you execute this command to make sure
# the latest kernel is installed and running successfully.
#
# If you get an error, make sure you are running the
# current kernel version, i.e. upgrade then reboot.
#
# Note: The plus (+) sign behind a package name inverts the meaning.
# So in the commands below, the plus keeps the running kernel version.
# The uname command finds your actual kernel package version and type.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

apt-get remove --purge 'linux-image-[0-9].*' linux-image-$(uname -r)+
apt-get remove --purge 'linux-headers-[0-9].*' linux-headers-$(uname -r)+
update-grub2
