#!/bin/bash
#
# Set apt to do automatic upgrades.
#
# This creates the file:
#
#    /etc/apt/apt.conf.d/20auto-upgrades 
#
sudo apt-get install -y unattended-upgrades
sudo apt-get install -y update-notifier-common
sudo dpkg-reconfigure -plow unattended-upgrades
