#!/bin/sh

##
# Use AWS Cloudfront list distributions,
# then select a specific one by alias name.
#
# Syntax:
#
#     aws-cloudfront-list-distributions-select-by-alias-name \
#       <alias name>
#
# Example:
#
#     aws-route53-list-resource-record-sets-then-select-by-name \
#       "demo.example.com"
##

name="$1"

aws cloudfront list-distributions |
jq --arg name "$name" -r '.DistributionList.Items[] | select(.Aliases.Items[] == ($name))'
