#!/bin/bash
set -euf -o pipefail
out () { printf %s\\n "$*" ; }

##
# brew reset clean
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-02-06
##

cd $(brew --prefix) &&
git reset --hard FETCH_HEAD &&
git clean -df

out "Optionally run these:"
out "brew --config"
out "brew --prefix"
out "brew doctor"
out "ls -ld \$(brew --prefix)"
out "ls -la \$(brew --prefix)"
out "cd \$(brew --prefix) && sudo chown $USER .git Library"
