#!/bin/bash
set -euf -o pipefail

##
# Brew is a MacOSX package manager.
#
# This script does some simple first aid
# to repair the brew repository then update.
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

cd `brew --prefix`
git remote add origin https://github.com/mxcl/homebrew.git
git fetch origin
git reset --hard origin/master
brew update
