#!/bin/sh
set -eufx -o pipefail

##
# Brew up everything we can.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

brew update
brew upgrade
brew-cask
brew cleanup
brew cask cleanup
