#!/usr/bin/env ruby

##
# Convert text to camel-case.
#
# Example:
#
#     $ echo "foo_goo_hoo" | camelize
#     FooGooHoo
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

require 'rubygems'
require 'active_support/inflector'
puts ARGV.map{|s| s.camelize}.join(' ')
