#!/bin/bash
#
# For each directory, change into the directory,
# and run a command.
#
set -o nounset
set -o errexit
set -o pipefail

unset CDPATH
while read dir ; do
  echo "$dir"
  cd "$dir"
  if [ $? -eq 0 ]
  then
    `"$@"`
    cd "$OLDPWD"
  fi
done
