#!/bin/bash
set -euf -o pipefail

##
# For each directory, change into the directory,
# and run a command.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

unset CDPATH
while read dir ; do
  echo "$dir"
  cd "$dir"
  if [ $? -eq 0 ]
  then
    `"$@"`
    cd "$OLDPWD"
  fi
done
