#!/bin/bash
set -euf -o pipefail

##
# Print some command line color examples.
# This is useful for reference.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

NORMAL=$(tput sgr0)
INFO=$(tput setaf 2; tput bold)
WARN=$(tput setaf 3)
FAIL=$(tput setaf 1)

function info() {
    echo -e "$GREEN$*$NORMAL"
}

function warn() {
    echo -e "$YELLOW$*$NORMAL"
}

function fail() {
    echo -e "$RED$*$NORMAL"
}

info "Hello world"
warn "Hello World"
fail "Hello World"
