#!/bin/sh
#
# convert-ico-to-png
#
# Convert an ICO image file to a PNG image file.
#
# Syntax:
#
#   convert-ico-to-png [ico input file name] [png output file name] [pixel width]
#
# Example:
#
#   convert-ico-to-png foo.ico foo.png 32
#
# Options:
#
#   * ico file name: default is "favicon.ico"
#   * png file name: default is "favicon.png"
#   * pixel width: default is 16.
#
# Requirements:
#
#   * The `convert` command, typically provided by ImageMagick.
#
# Command: convert-ico-to-png
# Version: 1.2.0
# Created: 2015-05-30
# Updated: 2016-02-14
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf

input_file_name=${1-"favicon.ico"}
output_file_name=${2-"favicon.png"}
pixel_width=${3:-"16"}
convert "$input_file_name" -thumbnail "${pixel_width}x${pixel_width}" -alpha on -background none -flatten "$output_file_name"
