#!/bin/sh

##
# Curl script to download a favicon from Google's service.
#
# Syntax:
#
#     curl-favicon <domain> 
#
# Example:
#
#     curl-favicon www.sixarm.com
#     => download www.sixarm.com favicon to file www.sixarm.com.png
##

if [ $# -eq 0 ]
then
  echo "Syntax: curl-favicon <domain>"
  echo "Example: curl-favicon www.sixarm.com sixarm.png"
  exit
fi

curl -s "http://www.google.com/s2/favicons?domain=$1" > "$1.png"

