#!/bin/sh
#
# curl-favicon downloads a favicon from Google's service
#
# Syntax:
#   curl-favicon <host> <file>
#
# Example:
#   curl-favicon www.sixarm.com sixarm.png
#   => download www.sixarm.com favicon to file sixarm.png
#
# Syntax Shorthand:
#   curl-favicon <site>
#   => download www.site.com favicon to site.png

if [ $# -eq 0 ]
then
  echo "Syntax: curl-favicon <domain> <filepath>"
  echo "Example: curl-favicon www.sixarm.com sixarm.png"
  exit
fi

if [ $# -eq 1 ]
then
  domain="www.$1.com"
  path="$1.png"
else
  domain=$1
  path=$2
fi

curl -s "http://www.google.com/s2/favicons?domain=$domain" > "$path"
echo "$domain => $path"
