#!/bin/sh
set -euf -o pipefail

##
# Print the current date stamp UTC in the shortest format.
#
# Example:
#
#     $ date-stamp-shortest
#     20001231125959
#
# See:
#
#     date-stamp
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

date -u "+%Y%m%d%H%M%S" "$@"
