#!/bin/sh
#
# Compare the list of filenames in the `spec` directory and `app directory.
#
# This is useful for discovering specs files that need app implementation,
# and also app implemenations that are missing corresponding spec files.
#
# This trims off the leading directory name (i.e. "app/" or "spec/"),
# and also trims off the basename suffix (e.g. "_spec.rb" or ".rb")
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
#
diff  \
<(find spec -type f | sed 's#^[^/]+/##; s#_spec\.[[:alnum:]]\+$##') \
<(find app  -type f | sed 's#^[^/]+/##; s#\.[[:alnum:]]\+$##')
