#!/bin/bash
set -euf -o pipefail

##
# Print lines that are only in file 2.
#
# Example:
#
#     cat 1.txt
#     a
#     b
#
#     cat 2.txt
#     b
#     c
#
#     diff-2 a.txt b.txt
#     c
#
# Credit: http://stackoverflow.com/questions/4717250/extracting-unique-values-between-2-sets-files
#
# This script is logically the same as:
#
#     comm -13 <(sort 1.txt) <(sort 2.txt)
#
# This script is faster than comm (especially on large files)
# because this script doesn't need the inputs to be sorted.
#
# Explanation:
#
#   * FNR is the current file's record number
#   * NR is the current overall record number
#   * FNR==NR is true when we are reading file1, not file2
#   * $0 is the line text
#   * a[$0] is a hash that tracks that we've seen the line text
#   * FNR==NR{a[$0];next} tracks that we've seen all the file1 line text
#   * !($0 in a) is true when we have not seen the line text
#   * awk default is to print the line text
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

awk 'FNR==NR{a[$0];next}!($0 in a)' "$@"
