#!/bin/sh
#
# dpkg-remove-damaged-libqt-DANGER
#
set -o nounset
set -o errexit
set -o pipefail

dpkg -r --force-all \
 indicator-appmenu \
 libdconf-dbus-1-0 \
 libdconf-qt0 \
 libqt4-dbus \
 libqt4-declarative \
 libqt4-declarative-folderlistmodel \
 libqt4-declarative-gestures \
 libqt4-declarative-particles \
 libqt4-declarative-shaders \
 libqt4-designer \
 libqt4-dev \
 libqt4-opengl-dev \
 libqt4-script \
 libqt4-scripttools \
 libqtbamf1 \
 libqtcore4 \
 libqtdee2 \
 libqtgconf1 \
 libqtgui4 \
 libunity-2d-private0 \
 qt4-dev-tools \
 qt4-doc \
 qt4-qmlviewer \
 qt4-qtconfig \
 ubuntu-desktop \
 unity-2d \
 unity-2d-panel \
 unity-2d-shell \
 unity-2d-spread \
 unixodbc-dev

dpkg --purge \
 indicator-appmenu \
 libdconf-dbus-1-0 \
 libdconf-qt0 \
 libqt4-dbus \
 libqt4-declarative \
 libqt4-declarative-folderlistmodel \
 libqt4-declarative-gestures \
 libqt4-declarative-particles \
 libqt4-declarative-shaders \
 libqt4-designer \
 libqt4-dev \
 libqt4-opengl-dev \
 libqt4-script \
 libqt4-scripttools \
 libqtbamf1 \
 libqtcore4 \
 libqtdee2 \
 libqtgconf1 \
 libqtgui4 \
 libunity-2d-private0 \
 qt4-dev-tools \
 qt4-doc \
 qt4-qmlviewer \
 qt4-qtconfig \
 ubuntu-desktop \
 unity-2d \
 unity-2d-panel \
 unity-2d-shell \
 unity-2d-spread \
 unixodbc-dev

echo "dpkg has removed damaged libqt files, including ubuntu-desktop etc."
echo "you probably want to run this immediately:"
echo
echo "    apt-get -f dist-upgrade"
