#!/bin/sh
set -euf -o pipefail

##
# Disk usage triage.
#
#   -S to omit subdir size
#
# Then sorted and limited to top 25
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

du -SPx . | sort -nr | head -25
