#!/bin/sh

##
# Sync files via the commands `entr` and `rclone`.
#
# Syntax:
#
#     entr-rclone <dir> <service>
#
# Example:
#
#     entr-rclone ~/foo dropbox
#
# See http://lpan.io/one-liner-dropbox-client/
#
#
# ## Make the script into a daemon
#
# For example you can create a systemd service file:
#
#     ~/.config/systemd/user/dropbox.service
#
# Example file:
#
#     [Unit]
#     Description=Dropbox Daemon
#
#     [Service]
#     ExecStart=/home/lpan/sync_dropbox.sh
#     Restart=always
#
#     [Install]
#     WantedBy=default.target
#
# Then you can manage the daemon with the following commands:
#
#     # reload the service file
#     systemctl --user daemon-reload
#
#     # start the daemon
#     systemctl --user start dropbox.service
#
#     # start the daemon on login
#     systemctl --user enable dropbox.service
#
#     # inspect the status of the daemon
#     systemctl --user status dropbox.service
#
# ## incron alternative
#
# Instead of using entr and systemd, you can use incron to
# watch for file changes, and use rclone in incrontab for syncing.
#
# See  https://kanihal.wordpress.com/2018/12/21/incron-and-rclone-for-syncing-screenshots-to-google-drive/
##

dir="$1"
remote="$2"
find "$dir" | entr -r rclone sync -v "$dir" "$remote:org"
