#!/bin/bash
set -euf -o pipefail
out () { printf %s\\n "$*" ; }

##
# Extract a file using best-guess of tar, bzip, rar, gz, zip, etc.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

if [ -f $1 ]; then
case $1 in
*.tar.bz2)   tar xjf $1 ;;
*.tar.gz)    tar xzf $1 ;;
*.bz2)       bunzip2 $1 ;;
*.rar)       unrar e $1 ;;
*.gz)        gunzip $1 ;;
*.tar)       tar xf $1 ;;
*.tbz2)      tar xjf $1 ;;
*.tgz)       tar xzf $1 ;;
*.zip)       unzip $1 ;;
*.Z)         uncompress $1 ;;
*.7z)        7z x $1 ;;
*)           out "'$1' cannot be extracted via extract()" ;;
esac
else
out "'$1' is not a valid file"
fi
