#!/bin/sh
set -euf -o pipefail
out () { printf %s\\n "$*" ; }

##
# Download a favicon.
#
# Syntax:
#
#     fetch-favicon <url>
#
# Example:
#
#     fetch-favicon www.example.com
#     => download favicon to file
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-06-30
##

if [ $# -eq 0 ]
then
  out "Syntax: fetch-favicon <url>"
  out "Example: fetch-favicon www.example.com"
  exit
fi

page_url=$1
out "page_url:$page_url"

icon_url=$(curl -s -S -L "$page_url" | pup 'link[rel~="icon"] attr{href}' | head -1)
out "icon_url:$icon_url"

icon_file_name=$(out "$icon_url" | uri-scheme file)
out "icon_file_name:$icon_file_name"

icon_abs_url=$(uri-relate "$page_url" "$icon_url")
out "icon_abs_url:$icon_abs_url"

curl -s -S -L "$icon_abs_url" -o "$icon_file_name"
