#!/bin/sh
#
# For each file name, run a command with the file name.
#
# Program: filedo
# Version: 1.1.3
# Created: 2012-05-26
# Updated: 2016-02-04
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
out () { printf %s\\n "$*" ; }

unset CDPATH
while read file_name
do
  out "$file_name"
  "$@" "$file_name"
done
