#!/bin/bash
set -euf -o pipefail
out () { printf %s\\n "$*" ; }

##
# Print a file's line at a given line number.
#
# Syntax:
#
#     file-line-num <file path> <line number> [line number] ...
#
# Example:
#
#     file-line-num myfile.txt 10
#     => prints line 10 of myfile.txt
#
# Example:
#
#     file-line-num myfile.txt 10 20 30
#     => prints line 10 of myfile.txt then line 20 then line 30
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

file_path="$1"
shift
for line_num; do
  out "$line_num p" | ed -s "$file_path"
done
