#!/bin/bash
set -euf -o pipefail

##
# For each file name, run a command with the file name.
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

unset CDPATH
while read file_name
do
  echo "$file_name"
  "$@" "$file_name"
done
