#!/bin/sh
set -euf -o pipefail

##
# Convert encoding of a file to unix utf-8
#
# Syntax:
#
#     file-encode-utf-8 foo.txt
#
# Useful for data files that contain what would be usable ascii text
# but are encoded as mpeg or some other encoding that prevents you
# from doing common manipulations like 'sed'
#
# See http://www.commandlinefu.com/commands/view/1029/convert-file-type-to-unix-utf-8
#
# Sample output:
#
#     $ file datafile1.csv
#     datafile1.csv: MPEG ADTS, layer I, v1, 160 kBits, 32 kHz, Stereo
#     $ file-encode-utf-8
#     $ file datafile1.csv
#     datafile1.csv: Unicode text, UTF-8
#
# How this works:
#
#   * Run `ex` which is typically the `vi` editor, or `vim`, or equivalent.
#   * Set the file format to unix
#   * Set the file encoding to UTF-8
#   * "+x" means save the file and exit.
#
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

ex $1 "+set ff=unix fileencoding=utf-8" "+x"
