#!/bin/bash
#
# Find (and print) all symbolic links without a target within the current dirtree
#
# From http://grml.org/zsh/zsh-lovers.html
#
set -o nounset
set -o errexit
set -o pipefail

file **/*(D@) | fgrep broken
for i in **/*(D@); [[ -f $i || -d $i ]] || echo $i
echo **/*(@-^./=%p)
print -l **/*(-@)
