#!/bin/bash
set -euf -o pipefail

##
# Find (and print) all symbolic links without a target within the current dirtree
#
# From http://grml.org/zsh/zsh-lovers.html
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

file **/*(D@) | fgrep broken
for i in **/*(D@); [[ -f $i || -d $i ]] || echo $i
echo **/*(@-^./=%p)
print -l **/*(-@)
