#!/bin/sh
set -euf -o pipefail

##
# Find broken symlinks.
#
# From http://scotgate.org/2007/03/04/howto-find-broken-symbolic-links-gentoo-linux-wiki/
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

find $1 -type l | (while read FN ; do test -e "$FN" || echo "$FN"; done)
