#!/bin/bash
set -euf -o pipefail

##
# Find a Thinkpad's TrackPoint speed file that sets the pointer speed.
#
# From http://zedic.com/thinkpad-trackpoint-speed-linux.html
# See also http://sourceforge.net/projects/tpctl/
#
# See also:
#
#     find-trackpoint-path-id
#     find-trackpoint-device-file-for-sensitivity
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

find "/sys/devices/platform/i8042/" -iname speed -type f
