#!/bin/sh

##
# Find all git repositories in a directory.
#
# Compare the script `find-git-repos-fast` in this same repo,
# which optimizes the search by using functions, and runs 2x faster.
#
# Credits:
#   * [vaab](http://stackoverflow.com/users/458681/vaab)
#   * http://stackoverflow.com/questions/11981716/how-to-quickly-find-all-git-repos-under-a-directory
##

find ${1:-.} -type d \( -exec test -d "{}/.git" -a "{}" != "." \; -print -prune -o -name .git -prune \)
