#!/bin/sh
set -euf -o pipefail

##
# Find items in the current directory and below,
# and delete all spaces in the file names.
#
# This script requires the `rename` command.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

find . -print0 | xargs -0 rename 's/ //g'
