#!/bin/sh
#
# font-file-to-full-name:
# given a font file, output the full name.
#
# This script is implemented on OS X by using `otfinfo`.
# To get this, use `brew install lcdf-typetools`.
#
# To Do:
#
#   * Implement on Linux and Windows
#   * Get other font fields
#
# Command: font-file-to-full-name
# Version: 1.1.0
# Created: 2015-12-19
# Updated: 2016-02-16
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf -o pipefail
otfinfo --info "$1" | sed -n 's/Full name: *//p'`
