#!/bin/sh
#
# font-file-to-family:
# given a font file, output the family name.
#
# This script is implemented on OS X by using `otfinfo`.
# To get this, use `brew install lcdf-typetools`.
#
# To Do:
#
#   * Implement on Linux and Windows
#   * Get other font fields
#
# ## Tracking
#
# * Command: font-file-to-family
# * Version: 1.1.1
# * Created: 2015-12-19
# * Updated: 2017-04-12
# * Command: font-file-to-family
# * License: GPL
# * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
otfinfo --info "$1"| sed -n 's/^Preferred family: */1/p; s/^Family: */2/p' | sort -u | head -1 | sed 's/^.//'
