#!/bin/sh
set -euf -o pipefail

##
# Given a font file, output the family name.
#
# This script is implemented on OS X by using `otfinfo`.
# To get this, use `brew install lcdf-typetools`.
#
# To Do:
#
#   * Implement on Linux and Windows
#   * Get other font fields
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2016-01-02
##

otfinfo --info "$1"| sed -n 's/^Preferred family: */1/p; s/^Family: */2/p' | sort -u | head -1 | sed 's/^.//'
