#!/bin/sh
set -euf -o pipefail

##
# Gem script to run all the test files.
#
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

ruby -rubygems -Ilib -Itest test/*.rb
