#!/bin/sh
set -euf -o pipefail

##
# Parse a typical Ruby Gemfile to a list of gem names.
#
# Example:
#
#     $ cat Gemfile | gemfile-to-gem-names
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

sed -n "s/^\s*gem\s+['"]\([^'"]*\)['"].*/\1/p"
