#!/bin/sh

for dir in *
do
  echo $dir
  cd $dir 
  [ -e LICENSE.txt ] && git add LICENSE.txt
  [ -e *.gem ] && git add *.gem
  [ -e .sha256.txt ] && rm .sha256.txt
  ~/github/sixarm_unix_git_tools/git-config-origin-master 
  git pull
  git commit -am 'update'
  git push
  git status
  cd -
done
