#!/bin/bash
#
# Fetch a GitHub user's email address,
# if it's in the user's profile.
#
set -o nounset
set -o errexit
set -o pipefail

curl -s https://api.github.com/users/$1/events/public | grep "\"email\":" | sed -e's/[,|"]//g' | sort | uniq -c | sort -n | awk '{print $(NF)}' | grep -v null
