#!/bin/bash
set -euf -o pipefail

##
# Gnome UI set power idel dim time in seconds.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

len=${1-600}
gsettings set org.gnome.settings-daemon.plugins.power idle-dim-time $seconds
