#!/bin/sh
set -euf -o pipefail

##
# GPG script to decrypt a file with our typical settings.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-12-20
##

umask_save=`umask`
umask 0077
gpg -d --no-greeting --no-use-agent --quiet $@
umask $umask_save
