#!/bin/bash
set -euf -o pipefail

##
# grep without web chaff like lines that have .css, .js, .png.
# This is useful e.g. for grepping web server log files.
#
# If you're using this, you may be interested in trying
# a newer search tool called The Silver Searcher.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

grep -v "\.\(bmp\|css\|gif\|ico\|jpg\|js\|png\)\b"
