#!/bin/bash
set -euf -o pipefail

##
# Convert the first <h1> link in a stream to an HTML list item.
# This is useful for building a table of contents for a bunch of files.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

grep -m1 "<h1>" *.html | sed 's#^\(.*\):<h1>\(.*\)</h1>#<li><a href="\1">\2</a>#'
