#!/bin/sh
set -euf -o pipefail

##
# Parse HTML to extract the favicon URL.
#
# Syntax:
#
#     ... | html-to-favicon-href
#
# Example:
#
#     wget http://example.com | html-to-favicon-href
#     => http://example.com/favicon.ico
#
# This implementation requires Ruby and the Nokogiri gem.
#
# We have tried other implementations, such as using hxselect
# or xmlstarlet, but these failed on various real-world web pages
# because of malformed HTML.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-05-25
##

ruby -rnokogiri -p -e 'd=Nokogiri::HTML(STDIN.read); $_=""; puts d.xpath("//link[contains(concat(\" \", @rel, \" \"), \" icon \")]").first["href"]'
