#!/bin/sh
#
# Print the lines that are in all of the inputs.
#
# Syntax:
#
#     intersect <input> ...
#
# Examples:
#
#     intersect a.txt b.txt
#     => lines that are in both of the files.
#
#     intersect a.txt b.txt c.txt
#     => lines that are in all of the files.
#
# ## Specifics
#
# The order does not matter.
#
# ## Related
#
# These commands are related:
#
#   * `union`: print lines in (A union B)
#   * `intersect`: print lines in (A intersect B)
#   * `except`: print lines in (A except B) a.k.a. (A - B)
#   * `extra` : print lines in (A extra B) a.k.a. (B - A)
#
# ## Notes
#
# In set theory, this is (A intersect B).
#
# This command aims to be fast, not to sort.
#
# This command is currently implemented using `awk`.
#
# ## Tracking
#
# Program: intersect
# Version: 2.0.2
# Created: 2017-01-30
# Updated: 2017-01-30
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -eu
awk 'FNR==1{f+=1} seen[$0]+=1 {next} END { for (key in seen) { if (seen[key]==f) { print key } } }' "$@"
