#!/usr/bin/env ruby

##
# json-to-xml converts text from JSON to XML.
#
# Example:
#
#     cat example.json | json-to-xml > example.xml
#
# Command: json-to-xml
# Version: 3.0.0
# Created: 2011-10-30
# Updated: 2015-03-24
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
#
require 'json'
require 'xmlsimple'
text = ARGF.read
json = JSON.parse(text)
xml = XmlSimple.xml_out(json, 'NoAttr' => true)
puts xml
