#!/usr/bin/env ruby

##
# json-to-xml converts text from JSON to XML.
#
# Example:
#
#     cat example.json | json-to-xml > example.xml
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-03-24
##

require 'json'
require 'xmlsimple'
text = ARGF.read
json = JSON.parse(text)
xml = XmlSimple.xml_out(json, 'NoAttr' => true)
puts xml
