#!/bin/sh
set -euf -o pipefail -o xtrace

##
# Kill a process with a given user.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

kill -9 `lsof -t -u $1`
