#!/bin/bash
#
# Show diagnostic details about the linux version.
# I.e. tell me about the current operating system.
#
set -o nounset
set -o errexit
set -o pipefail

echo 'uname -a'
uname -a

for file in /etc/redhat-release /proc/version /etc/issue.net
do
  if [[ -e $file ]]
  then
    echo ''
    echo "cat $file"
    cat $file
  fi;
done

echo ''
echo 'lsb_release -a'
lsb_release -a
