#!/bin/bash

##
# Show diagnostic details about the linux version.
# I.e. tell me about the current operating system.
##

echo 'uname -a'
uname -a

for file in /etc/redhat-release /proc/version /etc/issue
do
  if [[ -e $file ]]
  then
    echo ''
    echo "cat $file"
    cat $file
  fi;
done

echo ''
echo 'lsb_release -a'
lsb_release -a


