#!/bin/bash
set -euf -o pipefail

##
# Show diagnostic details about the linux version.
# I.e. tell me about the current operating system.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

echo 'uname -a'
uname -a

for file in /etc/redhat-release /proc/version /etc/issue.net
do
  if [[ -e $file ]]
  then
    echo ''
    echo "cat $file"
    cat $file
  fi;
done

echo ''
echo 'lsb_release -a'
lsb_release -a
