#!/bin/sh
set -euf -o pipefail

##
# Show current active connections i.e. that say "ESTABLISHED".
#
# See http://danielmiessler.com/study/lsof/
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

lsof -i| grep ESTABLISHED
