#!/bin/sh
set -euf -o pipefail

##
# This shows a MacBook Pro Retina screen model number.
# The modile number will be something like LP154YL01001.
#
#   * "LS" prefix: built by Samsung
#
#   * "LP" prefix: built by LG
#
# The screens manufactured by LG have had many problems with ghosting and image retention.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

ioreg -lw0 | grep \"EDID\" | sed "/[^<]*</s///" | xxd -p -r | strings -6
