#!/bin/sh
set -euf -o pipefail

##
# Make a typical user's mail directory for qmail or postfix.
#
# This makes these directories:
#
#     Maildir/cur
#     Maildir/new
#     Maildir/tmp
#     Maildir/drafts
#     Maildir/sent
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

mkdir -p Maildir/{cur,new,tmp,drafts,sent}
