#!/bin/sh
set -euf -o pipefail

##
# Make the typical Maildir directories in /etc/skel
#
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

mkdir -p /etc/skel/Maildir/{cur,new,tmp}
