#!/bin/sh
# Mount a .iso file.
# N.b. “-o loop” lets you use a file as a block device
#
# Example:
#  mount-iso /path/to/file.iso 
#
# From http://blog.urfix.com/25-%E2%80%93-sick-linux-commands/

mount $1 /mnt/cdrom -oloop
