#!/bin/sh
set -euf -o pipefail

##
# Print this system's IP address via whatismyip.org
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

curl whatismyip.org;echo
