#!/bin/sh
set -euf -o pipefail

##
# Input a list of numbers, output the maximum value.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

awk 'NR == 1 || $1 > max { max = $1 } END { print max }'