#!/bin/sh
set -euf -o pipefail

##
# Input a list of numbers, output the median.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

sort -n |
awk '{ a[NR] = $1 }
END {
  if (NR % 2) {
    median = a[(NR + 1) / 2];
  } else {
    median = (a[(NR / 2)] + a[(NR / 2) + 1]) / 2.0;
  }
  print median
}'
