#!/bin/sh
set -euf -o pipefail

##
# Input a list of numbers, output the range.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##
##

awk '
NR == 1 {
  min = $1
  max = $1
}
{
  if ($1 < min) { min = $1 }
  if ($1 > max) { max = $1 }
}
END {
  range = max - min
  print range
}'
