#!/bin/sh
set -euf -o pipefail

##
# Input a list of numbers, output the standard deviation.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

awk '{ sum += $1; a[NR] = $1 }
END {
  mean = sum/NR
  for (x = 1; x <= NR; x++){
    sumsq += (a[x] - mean) ** 2;
  }
  sd = sqrt(sumsq/NR)
  print sd
}'