#!/bin/sh
set -euf -o pipefail

##
# Input a list of numbers, output the sum.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

awk '{ sum += $1 }; END { print sum }'
