#!/bin/sh
set -euf -o pipefail

##
# Shorthand to use netstat to listen and print our typical output.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

netstat -ltnp
