#!/bin/sh
#
# Normalize a title string, suitable for alphabetizing and comparing.
#
# This script processes each input line and massages it like this:
#
#   * Smush whitespace runs to one space.
#   * Strip leading/trailing whitespace.
#   * Strip parentheticals.
#   * Strip extraneous characters: ™ © ®
#   * Strip leading stop words: A, The, etc.
#   * Strip trailing stop words after a comma.
#
# ## Tracking
#
#   * Command: normalize-title
#   * Version: 1.1.0
#   * Created: 2017-05-27
#   * Updated: 2017-06-17
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
#
sed -E " \
s/[[:space:]]+/ /g; \
s/^[[:space:]]+//; s/[[:space:]]+$//; \
s/\([^\)]*\)//g; \
s/ *[™©®] *//g; \
s/^ *(A|An|The) +//; s/ *, *(A|An|The) *$//; \
"
