#!/bin/sh
#
# OpenSSL script to generate a new key file for SixArm.com

openssl req -x509 -nodes -days 1000 -subj '/C=US/ST=California/L=San Francisco/O=SixArm/CN=sixarm.com' -newkey rsa:1024 -keyout sixarm-rsa1024-x509-private.pem -out sixarm-rsa1024-x509-public.pem
