#!/bin/bash
set -euf -o pipefail

##
# OpenSSL connect to a server,
# retrieve it's x509 certificate,
# and show the dates that are valid.
#
# Example:
#
#    $ echo | openssl s_client -connect google.com:443 2>/dev/null | openssl x509 -noout -dates
#    notBefore=Feb 12 14:58:10 2014 GMT
#    notAfter=Jun 12 00:00:00 2014 GMT
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

echo | openssl s_client -connect "$1" 2>/dev/null | openssl x509 -noout -dates
