#!/bin/bash
set -euf -o pipefail

##
# OpenSSL script to generate a new key file
# specifically for our SixArm.com company.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-03-14
##

name="sixarm-rsa-4096-x509-$(date -u "+%Y%m%d")"
subj="/C=US/ST=California/L=San Francisco/O=SixArm/CN=sixarm.com"
openssl req -x509 -nodes -days 1000 -subj "$subj" -newkey rsa:4096 -keyout $name-private.pem -out $name-public.pem
