#!/bin/bash
set -euf -o pipefail

##
# How to enter a password using shell script.
#
# You will want to customize this script by adding your own
# code to do whatever you want, once you have the password.
#
# This code works cross-platform: in bash, zsh, etc.
#
# Thanks to Stephane Chazelas for posting this solution.
# See http://board.issociate.de/thread/458978/how-to-enter-password-using-shell-script.html
#
# Implementation:
#
#   1. Store the STTY.
#   2. Prompt the user for a password
#   3. Restore the STTY.
#
# Result:
#
#   * The user's password is now in the shell variable $password
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

{
old_settings=$(stty -g)
stty -echo
printf 'password: '
IFS= read -r password
stty "$old_settings"
} <> /dev/tty >&0

# Write your own script code here to do
# whatever you want with the password.
#
# For example, to echo the password (which would be bad)
# echo $password
