#!/bin/bash
#
# Remove path(s) from the PATH environment variable.
#
# Usage: rmpath paths...
#
# From http://pastie.org/591350
#
set -o nounset
set -o errexit
set -o pipefail

for p in "$@"
do
    p=${p%"${p##*[!/]}"} ## remove trailing slashes
    case $PATH in
        "$p":*) PATH=${PATH#$p:} ;; ## at beginning of PATH
        *:"$p") PATH=${PATH%:$p} ;; ## at end of PATH
        *:"$p":*) PATH=${PATH%":$p"*}${PATH##*"$p"} ;;
    esac
done
export PATH
