#!/bin/sh
set -euf -o pipefail

##
# pmset-drawing-battery: is the power manager drawing from battery power?
#
# Example:
#
#     pmset-drawing-battery && echo "yes" || echo "no"
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-06-30
##

pmset -g ps | grep  -q " drawing from 'Battery Power'"
