#!/bin/sh
set -euf -o pipefail

##
# pmset-drawing: what is the power manager drawing from?
#
# The known values are:
#
#   * "Now drawing from 'AC Power'"
#   * "Now drawing from 'Battery Power'"
#
# Example:
#
#     pmset-drawing
#     Now drawing from 'AC Power'
#
# See also:
#
#   * `pmset-drawing-ac`
#   * `pmset-drawing-battery`
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-06-30
##

pmset -g ps | head -1
