#!/bin/sh
set -euf -o pipefail

##
# pmset-battery-percent: Show the internal battery % charged.
#
# Example:
#
#     pmset-battery-percent
#     100
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-07-01
##

pmset -g batt | grep 'InternalBattery-0' | sed -n 's/.*[^[:digit:]]\([[:digit:]]\+\)%.*/\1/p'
