#!/bin/sh
set -euf -o pipefail

##
# pmset-battery-full: Is the internal battery fully charged?
#
# Example:
#
#     pmset-battery-full && echo "yes" || echo "no"
#     yes
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-07-01
##

pmset -g batt | grep 'InternalBattery-0' | grep -q '100%'
