#!/bin/sh
port="$1"

cmd() { command -v $1 >/dev/null 2>&1 ; }; export -f cmd

if $(cmd "ss"); then
    case $(uname) in
	*)
	    ( set -x; sudo ss -lptn 'sport = :$port' )
	    ;;
    esac
fi

if $(cmd "lsof"); then
    case $(uname) in
	*)
	    ( set -x; sudo lsof -n -i :$port )
    esac
fi

if $(cmd "netstat"); then
    case $(uname) in
	"Darwin")
	    :
	    ;;
	*)
	    ( set -x; sudo netstat --numeric --listening --program | grep "[^[:digit:]]80[^[:digit:]]" )
	    ;;
    esac
fi

if $(cmd "fuser"); then
    case $(uname) in
	"Darwin")
	    :
	    ;;
	*)
	    ( set -x; fuser -v -n tcp $port )
	    ;;
    esac
fi

if $(cmd "sockstat"); then
    case $(uname) in
	*)
	    ( set -x; sockstat -4 -l | grep ":$port[^[:digit:]]" | awk '{print $3}' | head -1 )
	    ;;
    esac
fi
