#!/bin/bash
set -euf -o pipefail

##
# How many meta-programming methods are in your Rails project?
#
# This script counts the occurences of these methods:
#   * eval
#   * method_missing
#   * define_method
#   * instance_variable_set
#
# The result can be useful as a guesstimate of how hard
# the code may be to maintain, analyze, port, and update:
#   * Single digits are best.
#   * Double digits should give pause.
#   * Triple digits should scare you.
#   * Quadruple digits mean run for the hills.  :)
#
# To use this metric on Ruby code that isn't a Rails project,
# or on code that isn't within the directories app/ or lib/,
# we use the script ruby-metaprogramming-metric which lets
# us input arbitrary files.
#
# Based on http://aaronblohowiak.com/rails-maintainability-metric
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

find app/** lib/** | grep "\b\(eval\|method_missing\|define_method\|instance_variable_set\)\b"  | wc -l
