#!/bin/bash

##
# Rails script to do a simple deployment from the command line.
##

git pull
git submodule update --init --recursive
bundle install
bundle update sprockets
bundle rake db:migrate
bundle rake db:seed
touch tmp/restart.txt
