#!/bin/bash
set -euf -o pipefail

##
# Run our typical Rails test files
#
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

RAILS_ENV=test ruby -Itest "$@"
