#!/bin/bash
set -euf -o pipefail

##
# Shows the word count of each file in a Rails app subdirectory.
#
# This is a code weight bash one-liner for rails by James Golick.
# It's good for a quick estimate of which files contain the most code.
#
# Syntax:
#
#     rails-word-counts models
#
# Example in a Rails top level directory:
#
#     $ rails-word-count models
#       368 app/models/user.rb
#        98 app/models/team.rb
#        71 app/models/post.rb
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

for file in $(find app/$1/**/*.rb -type f); do wc -l $file ; done  | sort -r
