#!/bin/bash
set -euf -o pipefail -o xtrace

##
# Rails script to update everything from origin master:
#
#   * pull from origin master
#   * update submodules (if applicable)
#   * bundle install
#   * rake db:migrate, db:seed, db:test:prepare
#   * restart the server (if applicable)
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

git pull origin master
git submodule update --init --recursive
bundle install
bundle exec rake db:migrate
bundle exec rake db:seed
bundle exec rake db:test:prepare
touch tmp/restart.txt
