#!/bin/sh
set -euf -o pipefail

##
# Generate a random LinkedIn app API key,
#
# The string is alphanumeric lowercase 12 characters.
#
# Usage:
#
#     random-linkedin-app-api-key
#
# Example:
#
#     $ random-linkedin-app-api-key
#     voqktpwdsopxq
#
# See http://linkedin.com
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-alphanum-lower 12
