#!/bin/bash
#
# Generate a random integer.
# Default is one digit 0 to 9.
#
# Usage: random-int [max] [count]
# * max is an optional exclusive maximum; it defaults to 10.
# Generate a random integer from 0 to an optional max.
#
# Example:
#   random-int
#   => a random integer from 0 to 9
#
# Example:
#   random-int 100
#   => a random integer from 0 to 99
#
# Example:
#   random-int 100 8
#   => eight random integers from 0 to 99
#
# This script seeds the bash random variable.
# To do this, use the random-seed script.
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
# License is GPL v2

# From random-seed script
seed=$(head -c4 /dev/urandom | od -t u4 | awk '{ print $2 }')
RANDOM=$seed

# From random-int-faster script
upper=${1-9}
count=${2-1}
echo "Count: $count"
for i in $(seq 1 $count)
do
  r=$[ ( $RANDOM % $upper ) ]
  echo $r
done
