#!/bin/bash
set -euf -o pipefail

##
# Generate a random Apple development id string.
#
# The string is alphanumeric, uppercase, 10 characters.
#
# Usage:
#
#     random-apple-development-id
#
# Example:
#
#     $ random-apple-development-id
#     YT4K6BX2UZ
#
# See http://developer.apple.com
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-alphanum-upper 10
