#!/bin/sh
set -euf -o pipefail

##
# Generate a random alphanumeric uppercase string.
#
# Usage:
#
#     random-alphanum-upper [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Example:
#
#     $ random-alphanum-upper
#     J8YUOHTPTYI8S4VK
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-match A-Z0-9 ${1-16}
