#!/bin/sh
set -euf -o pipefail

##
# Generate a secure random alphabetic lowercase string.
#
# Usage:
#
#     random-alpha-lower [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Example:
#
#     $ random-alpha-lower
#     ecwqibeuxtyukoja
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-match a-z ${1-16}
