#!/bin/bash
set -euf -o pipefail

##
# Generate a random Twitter app consumer key.
#
# The string is alphanumeric, mixed case, 21 characters.
#
# Usage:
#
#     random-twitter-app-consumer-key
#
# Example:
#
#     $ random-twitter-app-consumer-key
#     NIqmCufaqpSvKyYXMRMaF
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##


random-alphanum 21
