#!/bin/bash
#
# Shell script to generate a random hex fingerprint.
# This uses the commands `hexdump` and `urandom`.
#
# Usage: random-hex-fingerprint [n]
#
#   * n is an optional length in bytes.
#     It defaults to 16 bytes, which is typical of
#     fingerprints for ssh DSA, ECDSA, and RSA.
#
# Example:
#
#     $ random-hex-fingerprint 
#     73:5C:6E:83:75:80:E4:04:7A:AE:AC:BA:EE:46:E6:43
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
# License is GPL v2
#
set -o nounset
set -o errexit
set -o pipefail

len=${1-16}
hexdump -n $len -e "$len/1 \"%02X:\"" /dev/random | sed 's/:$//'
