#!/bin/bash

##
# Generate a secure random alphanumeric lowercase string.
#
# Usage:
#
#     random-alphanum-lower [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Example:
#
#     $ random-alphanum-lower
#     v08774zvxlf8layk
#   
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

random-match a-z0-9 ${1-16}
