#!/bin/bash

##
# Generate a random string of word characters.
#
# The characters are A-Z, a-z, and underscore.
#
# Usage:
#
#     random-word-characters [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Examples:
#
#     $ random-word-characters
#     UT_QPCfk_zhQNhpB
#
#     $ random-word-characters 8
#     YpGm_pmE
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

random-match _A-Za-z ${1-16}
