#!/bin/sh
set -euf -o pipefail

##
# Generate a secure random alphanumeric string.
#
# Syntax:
#
#     random-alphanum [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Example:
#
#     $ random-alphanum
#     RDv7pOB0Gr8s5kWd
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-match A-Za-z0-9 ${1-16}
