#!/bin/bash
set -euf -o pipefail

##
# Generate a secure random string.
#
# Usage:
#
#     random-match <characters> [n]
#
# Options:
#
#   * `characters` is a tr-compatible string.
#   * `n` is the number of characters; default is 1.
#
# Example:
#
#     random-match
#     #=> X
#
#     random-match A-Z 6
#     #=> ZMFKBT
#
# This implementation uses `/dev/random`
# and `tr` to select matching characters.
#
# Depending on your own systems and security needs,
# you may want to adjust this script by changing the
# system command `/dev/random` to `/dev/urandom`.
# This change will make the script non-blocking.
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

characters=$1
len=${2-1}
LC_ALL=C < /dev/random tr -dc "$characters" | head -c"$len"
