#!/bin/bash

##
# Generate a random Segment.io Analytics secret key string.
#
# The string is alphanumeric, lowercase, 10 characters.
#
# Usage:
#
#     random-segment-analytics-secret
#
# Example:
#
#     $ random-segment-analytics-secret
#     ilao5b9x5d
#
# See http://segment.com
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

random-alphanum-lower 10
