#!/bin/sh
set -euf -o pipefail

##
# Generate a random integer.
#
# Usage:
#
#     random-int [max] [count]
#
# Options:
#
#   * `max` is the exclusive maximum; default is 10.
#   * `count` is how many to generate, one per line of output
#
# Examples:
#
#     $ random-int
#     #=> a random integer from 0 to 9
#
#     $ random-int 100
#     #=> a random integer from 0 to 99
#
#     $ random-int 100 8
#     #=> eight random integers from 0 to 99
#
# This script seeds the bash random variable.
#
# Cf. random-seed
# Cf. random-int-faster
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

set -o nounset
set -o errexit
set -o pipefail

random-seed
random-int-faster $@
