#!/bin/bash
set -euf -o pipefail
out () { printf %s\\n "$*" ; }

##
# Generate a random password then encrypt it.
#
# Usage:
#
#     random-password-encrypt [filepath]
#
# The filepath default is "password",
# which then generates "password.gpg".
#
# Output:
#
#     <filepath>.gpg file with encrypted password.
#
# This uses two SixArm scripts:
#
#   * random-password to generate the password.
#   * gpg-encrypt to encrypt the password file.
#
# You need both of these for this script to work.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

filepath=${1-password}
password=`random-password`

if [[ -e "$filepath" ]]; then
  out  "The file path $filepath already exists"
  exit -1;
fi

out "$password" > "$filepath"
gpg-encrypt "$filepath"
rm "$filepath"
out "$password"
