#!/bin/bash
set -euf -o pipefail

##
# Generate a random Twitter app consumer secret.
#
# The string is alphanumeric, mixed case, 42 characters.
#
# Usage:
#
#     random-twitter-app-consumer-secret [n]
#
# Options:
#
#   * `n` is the number of characters; default is 42.
#
# Example:
#
#     $ random-twitter-app-consumer-secret
#     ksk6Xu4echm9qSCJsRdLOeK1TiJiceTWeJrY26U9V1
#
# See http://twitter.com
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-alphanum ${1-42}
