#!/bin/bash
#
# Shell script to generate a secure Amazon Web Services (AWS)
# Simple Email Service (SES) Simple Mail Transfer Protocol (SMTP)
# password, which seems to be a string of 43 letters and symbols.
#
# This uses urandom to pick from among A-Z, a-z, 0-9, +, /, chars.
#
# Usage: random-aws-ses-smtp-password [n]
# * n is an optional length; it defaults to 43.
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
# License is GPL v2

len=${1-43}
cat /dev/random | strings -n 1 | grep -o '[0-9A-Za-z\+\/]' | head -n $len | tr -d '\n'; echo
