#!/bin/bash

##
# Generate a random alphabetic uppercase string.
#
# Usage:
#
#     random-alpha-upper [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Example:
#
#     $ random-alpha-upper
#     JBXSTSCTUEREGJVH
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

random-match A-Z ${1-16}
