#!/bin/bash
set -euf -o pipefail

##
# Generate a random TestFlight API token string.
#
# The string is 32 character lowercase hex string,
# then a dash, then a 44 character alphanum string.
#
# See http://testflightapp.com
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

part1=`random-hex 16 | tr 'A-Z' 'a-z'`
part2=`random-alphaum 44`
echo "${part1}_${part2}"
