#!/bin/bash

##
# Generate a random LinkedIn app secret key string.
#
# The string is alphanumeric lowercase 16 characters.
#
# Syntax:
#
#     random-linkedin-app-secret-key [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Example:
#
#     $ random-linkedin-app-secret-key
#     PJDcwJFwD6KRFtTj
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

random-alphanum ${1-16}
