#!/bin/bash

##
# Generate a random hex string.
#
# Usage:
#
#     random-hex [n]
#
# Options:
#
#   * `n` is the number of bytes; default is 16.
#      Note that this means the output string is twice as long.
#
# Example:
#
#     $ random-hex
#     37004A3B3427BE452DDB8E681EAB58A6
#
# Alternate solution for Linux, using the tr command:
#
#     cat /dev/random | tr -cd '0-9A-F' | head -c 16; echo
#
# Alternate solution for BSD and Mac OS X, using the tr command:
#
#     cat /dev/random | env LC_CTYPE=C tr -cd '0-9A-F' | head -c 16; echo
#
# This implemenation uses the commands `hexdump` and `/dev/random`.
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

set -o nounset
set -o errexit
set -o pipefail

len=${1-16}
hexdump -n $len -v -e '/1 "%02X"' -e "/$len \"\n\"" /dev/random
