#!/bin/bash
#
# Generate a random integer.
#
# Usage: random-int [max] [count]
#
#   * max is the exclusive maximum; it defaults to 10.
#   * count is how many to generate, one per line of output
#
# Example:
#   random-int
#   => a random integer from 0 to 9
#
# Example:
#   random-int 100
#   => a random integer from 0 to 99
#
# Example:
#   random-int 100 8
#   => eight random integers from 0 to 99
#
# This script does NOT seed the bash random variable.
#
#   * To seed each time, use script random-int.
#   * To seed once, use the script random-seed.
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
# License is GPL v2

upper=${1-10}
count=${2-1}
for i in $(seq 1 $count)
do
  r=$[ ( $RANDOM % $upper ) ]
  echo $r
done
