#!/bin/bash
set -euf -o pipefail

##
# Generate random digits.
#
# Usage:
#
#     random-digits [n] [count]
#
# Options:
#
#   * `n` is the number of digits to generate on one line; default is 16.
#   * `count` is how many lines to generate; default is 1.
#
# Examples:
#
#     $ random-digits
#     #=> sixteen random digits
#
#     $ random-digits 3
#     #=> three random digits
#
#     $ random-digits 3 4
#     #=> three random digits, four times
#
# This script seeds the bash random variable.
#
# Cf. random-seed
# Cf. random-int-faster
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-seed
random-digits-faster $@
