#!/bin/bash
#
# Generate random digits.
#
# Usage: random-digits-faster [n] [count]
#
#   * n is how many digits to generate on one line; it defaults to 16.
#   * count is how many lines to generate; it defaults to 1.
#
# Example:
#   random-digits-faster
#   => sixteen random digits
#
# Example:
#   random-digits-faster 3
#   => three random digits
#
# Example:
#   random-digits-faster 3 4
#   => three random digits, four times 
#
# This script does NOT seed the bash random variable.
#
#   * To seed each time, use script random-digits.
#   * To seed once, use the script random-seed.
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
# License is GPL v2

n=${1-16}
count=${2-1}
for line in $(seq 1 $count) 
do 
  for i in $(seq 1 $n)
  do
    r=$[ ( $RANDOM % 10 ) ]
    echo -ne $r
  done
  echo
done
