#!/bin/bash
set -euf -o pipefail

##
# Generate a secure random alphabetic string.
#
# Usage:
#
#     random-alpha [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Example:
#
#     $ random-alpha
#     NcgCdRmnrspdDXuA
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-match A-Za-z ${1-16}
