#!/bin/bash
set -euf -o pipefail

##
# Generate a random Mixpanel.com token.
#
# This is a 32 character lowercase hex string.
#
# Usage:
#
#     random-mixpanel-token
#
# Example:
#
#     $ random-mixpanel-token
#     314aded16e28a4f9d16755ba9c6730bc
#
# See http://mixpanel.com
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-hex 16 | tr A-Z a-z
