#!/bin/bash
#
# Shell script to generate a random uuid.
#
# Usage: random-uuid
#
# Example:
#
#     $ random-uuid
#     63813D83-094B-4E15-A904-A28BB9CE51DB
#
# This script uses the commands `hexdump` and `urandom` 
# to generate secure random numbers and format them.
#
# If your system has the `uuidgen` tool, consider using it
# instead because it's faster; use the `-r` random flag.
#
# Example uuidgen on Linux:
#
#     $ uuidgen -r
# 
# By Joel Parker Henderson, joel@joelparkerhenderson.com
# License is GPL v2

hexdump -n 16 -v -e '4/1 "%02X" "-" 2/1 "%02X" "-" 2/1 "%02X" "-" 2/1 "%02X" "-" 6/1 "%02X" "\n"' /dev/urandom
