#!/bin/bash
set -euf -o pipefail

##
# Generate a random Segment.io Analytics secret key string.
#
# The string is alphanumeric, lowercase, 10 characters.
#
# Usage:
#
#     random-segment-analytics-secret
#
# Example:
#
#     $ random-segment-analytics-secret
#     ilao5b9x5d
#
# See http://segment.com
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-alphanum-lower 10
