#!/bin/bash
set -euf -o pipefail

##
# Generate a random LinkedIn app secret key string.
#
# The string is alphanumeric lowercase 16 characters.
#
# Syntax:
#
#     random-linkedin-app-secret-key [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Example:
#
#     $ random-linkedin-app-secret-key
#     PJDcwJFwD6KRFtTj
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-alphanum ${1-16}
