#!/bin/bash

##
# Generate random digits.
#
# Usage:
#
#     random-digits [n] [count]
#
# Options:
#
#   * `n` is the number of digits to generate on one line; default is 16.
#   * `count` is how many lines to generate; default is 1.
#
# Examples:
#
#     $ random-digits
#     #=> sixteen random digits
#
#     $ random-digits 3
#     #=> three random digits
#
#     $ random-digits 3 4
#     #=> three random digits, four times
#
# This script seeds the bash random variable.
#
# Cf. random-seed
# Cf. random-int-faster
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

set -o nounset
set -o errexit
set -o pipefail

random-seed
random-digits-faster $@
