#!/bin/bash
set -euf -o pipefail

##
# Generate a secure random alphanumeric lowercase string.
#
# Usage:
#
#     random-alphanum-lower [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Example:
#
#     $ random-alphanum-lower
#     v08774zvxlf8layk
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-match a-z0-9 ${1-16}
