#!/bin/bash

##
# Generate a secure random alphabetic lowercase string.
#
# Usage:
#
#     random-alpha-lower [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Example:
#
#     $ random-alpha-lower
#     ecwqibeuxtyukoja
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

random-match a-z ${1-16}
