#!/bin/bash
set -euf -o pipefail

##
# Generate a random Crittercism.com App Id string.
#
# The string is alphanumeric, lowercase, 24 characters.
#
# Usage:
#
#     random-crittercism-app-id
#
# Example:
#
#     $ random-crittercism-app-id
#     rh082vn0gapaqjitzszlnc46
#
# See http://crittercism.com
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-alphanum-lower 24
