#!/bin/bash
#
# Generate a random TestFlight team token string.
# This is a 32 character lowercase hex string,
# then a dash, then a 44 character alphanum string.
#
# For details, see http://testflightapp.com
#
part1=`random-hex 16 | tr 'A-Z' 'a-z'`
part2=`random-alphaum 44` 
echo "${part1}_${part2}"
