#!/bin/bash
set -euf -o pipefail

##
# Generate a random Etsy shop id string.
#
# The string is alphabetic, mixed case, 4-64 characters.
#
# Syntax:
#
#     random-etsy-shop-id [n]
#
# Options:
#
#   * `n` is the number of characters; default is 4-64.
#
# Example:
#
#     $ random-etsy-shop-id
#     oRcIJbwcwXHUVOyHPFeHTKicenPsxttC
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

n=${1-$(( $RANDOM % 60 + 4 ))}
echo $n
random-alpha $n
