#!/bin/bash

##
# Generate a random Twitter app consumer secret.
#
# The string is alphanumeric, mixed case, 42 characters.
#
# Usage:
#
#     random-twitter-app-consumer-secret [n]
#
# Options:
#
#   * `n` is the number of characters; default is 42.
#
# Example:
#
#     $ random-twitter-app-consumer-secret
#     ksk6Xu4echm9qSCJsRdLOeK1TiJiceTWeJrY26U9V1
#
# See http://twitter.com
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

random-alphanum ${1-42}
