#!/bin/sh
set -euf -o pipefail

##
# Generate a random hex MAC address.
#
# Usage:
#
#     random-mac-address [n]
#
# Options:
#
#   * `n` this the number of bytes; default is 6.
#
# Example:
#
#     $ random-mac-address
#     58:bc:f8:52:2b:c2
#
# This implementation uses `hexdump` and `/dev/random`.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

len=${1-6}
hexdump -n $len -e "$len/1 \"%02x:\"" /dev/random | sed 's/:$//'
