#!/bin/bash
set -euf -o pipefail

##
# Generate a random string of word characters.
#
# The characters are A-Z, a-z, and underscore.
#
# Usage:
#
#     random-word-characters [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Examples:
#
#     $ random-word-characters
#     UT_QPCfk_zhQNhpB
#
#     $ random-word-characters 8
#     YpGm_pmE
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-match _A-Za-z ${1-16}
