#!/bin/bash
#
# Generate a random integer.
# Default is one digit 0 to 9.
#
# Usage: random-int [max]
# * max is an optional exclusive maximum; it defaults to 10.
# Generate a random integer from 0 to an optional max.
#
# Example:
#   random-int
#   => a random integer from 0 to 9
#
# Example:
#   random-int 100
#   => a random integer from 0 to 99
#
# This script seeds the bash random variable.
# To do this, use the random-seed script.

# From random-seed script
seed=$(head -c4 /dev/urandom | od -t u4 | awk '{ print $2 }')
RANDOM=$seed

# From random-int-faster script
upper=${1-9}
r=$[ ( $RANDOM % $upper ) ]
echo $r

