#!/bin/bash
set -euf -o pipefail

##
# Seed the bash random number generator using /dev/random
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

RANDOM=$(head -c4 /dev/random | od -t u4 | awk '{ print $2 }')
