#!/bin/bash
#
# Shell script to generate a secure random alphanumeric string.
# This uses /dev/random to pick from among 0-9 and a-z chars.
#
# Usage: random-alphanum-lower [n]
# * n is an optional length; it defaults to 16.
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
#
set -o nounset
set -o errexit
set -o pipefail

len=${1-16}
cat /dev/random | strings -n 1 | grep -o '[0-9a-z]' | head -n $len | tr -d '\n'; echo
