#!/bin/bash

##
# Generate a secure random alphanumeric string.
#
# Syntax:
#
#     random-alphanum [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Example:
#
#     $ random-alphanum
#     RDv7pOB0Gr8s5kWd
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

random-match A-Za-z0-9 ${1-16}
