#!/bin/bash
#
# Generate a good password of four random words from a text file.
#
# Syntax:
#   random-password-with-words [file_path]
#
# Example:
#   random-password-with-words /usr/share/dict/passwords
#   => foo bar goo baz
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
# License is GPL v2

password_file_path=${1-/usr/share/dict/passwords}
n=`echo '$=' | ed -s "$password_file_path"`

# Pick 4 random line numbers
./random-seed
rand1=`./random-int-faster $n`
rand2=`./random-int-faster $n`
rand3=`./random-int-faster $n`
rand4=`./random-int-faster $n`

# Print the lines
./file-line-num "$password_file_path" $rand1 $rand2 $rand3 $rand4 | sed ':a;N;$!ba;s/\n/ /g'
