#!/bin/bash

##
# Generate a random hex MAC address.
#
# Usage:
#
#     random-mac-address [n]
#
# Options:
#
#   * `n` this the number of bytes; default is 6.
#
# Example:
#
#     $ random-mac-address
#     58:bc:f8:52:2b:c2
#
# This implementation uses `hexdump` and `/dev/random`.
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

len=${1-6}
hexdump -n $len -e "$len/1 \"%02x:\"" /dev/random | sed 's/:$//'
