#!/bin/bash
set -euf -o pipefail

##
# Generate random digits.
#
# Usage:
#
#     random-digits-faster [n] [count]
#
# Options:
#
#   * `n` is the number of digits to generate on one line; default is 16.
#   * `count` is how many lines to generate; default is 1.
#
# Examples:
#
#     $ random-digits-faster
#     #=> sixteen random digits
#
#     $ random-digits-faster 3
#     #=> three random digits
#
#     $ random-digits-faster 3 4
#     #=> three random digits, four times
#
# This script does NOT seed the bash random variable.
#
#   * To seed each time, use script random-digits.
#   * To seed once, use the script random-seed.
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

n=${1-16}
count=${2-1}
for line in $(seq 1 $count)
do
  for i in $(seq 1 $n)
  do
    r=$[ ( $RANDOM % 10 ) ]
    echo -ne $r
  done
  echo
done
