#!/bin/bash
#
# Generate random digits.
#
# Usage: random-digits [n] [count]
#
#   * n is how many digits to generate on one line; it defaults to 16.
#   * count is how many lines to generate; it defaults to 1.
#
# Example:
#   random-digits
#   => sixteen random digits
#
# Example:
#   random-digits 3
#   => three random digits
#
# Example:
#   random-digits 3 4
#   => three random digits, four times 
#
# This script seeds the bash random variable.
# Cf. random-seed
# Cf. random-int-faster
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
# License is GPL v2

./random-seed
./random-digits-faster $@
