#!/bin/sh
set -euf -o pipefail

##
# Generate a random Facebook app API secret.
#
# This is a random MD5 hash.
#
# Usage:
#
#     random-facebook-app-api-secret
#
# Example:
#
#     $ random-facebook-app-api-secret
#     489bfc1cbe3f7705b306a944917fcc94
#
# See http://facebook.com
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-md5
