#!/bin/bash

##
# Generate a random Amazon Web Services (AWS) Simple Email Service (SES)
# Simple Mail Transfer Protocol (SMTP) username string.
#
# The string is alphabetic, uppercase, 20 characters.
#
# Usage:
#
#    random-aws-ses-smtp-username
#
# Example:
#
#    $ random-aws-ses-smtp-username
#    SYEKEHQILMOKVIMZGRXJ
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

random-alpha-upper 20
