#!/bin/bash
set -euf -o pipefail

##
# Generate a random bcrypt salt string.
#
# The string is the prefix ''$2a$07$' then 22 alphanumeric characters.
#
# Usage:
#
#     random-bcrypt-salt [n]
#
# Options:
#
#   * `n` is the number of characters; default is 22.
#
# Example:
#
#     $ random-bcrypt-salt
#     $2a$07$PIcjwSQgSzExwIS4Qy9sOt
#
# Be aware that bcrypt uses this salt converted to base 64,
# which means that the final character may not be carrying
# information; in other words, two salts can differ in the
# final character yet still produce the same crypt text.
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

echo '$2a$07$'$(random-alphanum ${1-22})
