#!/bin/sh
set -euf -o pipefail

##
# Generate a random MD5 string.
#
# Usage:
#
#     random-md5
#
# Example:
#
#     $ random-md5
#     15e368b020138215126947ac5272aead
#
# This implementation uses `md5sum` or `md5`.
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

_md5=$(which md5sum md5 | grep -v "not found" | head -1)
dd if=/dev/random bs=1 count=32 2>/dev/null | $_md5 | sed 's/ .*//'
