#!/bin/bash
set -euf -o pipefail

##
# Generate a random UUID lowercase string.
#
# Usage:
#
#     random-uuid-lower
#
# Example:
#
#     $ random-uuid-lower
#     be09f214-7afa-4e51-bef5-6ead95071a37
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-uuid | tr A-F a-f
