#!/bin/bash
set -euf -o pipefail

##
# Generate a random Facebook app id string.
#
# The string is digits, 15 characters.
#
# Usage:
#
#     random-facebook-app-id
#
# Example:
#
#     $ random-facebook-app-id
#     567337611380931
#
# See http://facebook.com
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-digits 15
