#!/bin/bash
set -euf -o pipefail

##
# Generate a random Amazon Web Services (AWS) Simple Email Service (SES)
# Simple Mail Transfer Protocol (SMTP) username string.
#
# The string is alphabetic, uppercase, 20 characters.
#
# Usage:
#
#    random-aws-ses-smtp-username
#
# Example:
#
#    $ random-aws-ses-smtp-username
#    SYEKEHQILMOKVIMZGRXJ
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-alpha-upper 20
