#!/bin/bash

##
# Generate a Amazon Web Services (AWS) Simple Email Service (SES)
# Simple Mail Transfer Protocol (SMTP) password string.
#
# The string is alphanumeric and symbols "+" "/" and 43 characters.
#
# Usage:
#
#     random-aws-ses-smtp-password [n]
#
# Options:
#
#   * `n` is the number of characters; default is 43.
#
# Example:
#
#     $ random-aws-ses-smtp-password 
#     uj5\Tk47oqJ+YBSXxTaeZXnN/2N3rMfTwVU+np+f20
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

random-match 'A-Za-z0-9\+\/' ${1-43}
