#!/bin/bash
set -euf -o pipefail

##
# Generate a random TestFlight app_token string.
#
# The string is a uuid, lowercase.
#
# Usage:
#
#     random-testflight-app-token
#
# Example:
#
#     $ random-testflight-app-token
#     a49b80e8-8836-46a2-a7c6-5ab8f0ac9ddc
#
# For details, see http://testflightapp.com
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-uuid-lower
