#!/bin/bash
set -euf -o pipefail

##
# Generate a random alphabetic uppercase string.
#
# Usage:
#
#     random-alpha-upper [n]
#
# Options:
#
#   * `n` is the number of characters; default is 16.
#
# Example:
#
#     $ random-alpha-upper
#     JBXSTSCTUEREGJVH
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

random-match A-Z ${1-16}
