#!/bin/bash
set -euf -o pipefail

##
# Generate a random uuid string.
#
# Usage:
#
#     random-uuid
#
# Example:
#
#     $ random-uuid
#     63813D83-094B-4E15-A904-A28BB9CE51DB
#
# This script uses the commands `hexdump` and `/dev/random`
# to generate secure random numbers and format them.
#
# If your system has the `uuidgen` tool, consider using it
# instead because it's faster; use the `-r` random flag.
#
# Example uuidgen on Linux:
#
#     $ uuidgen -r
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

hexdump -n 16 -v -e '4/1 "%02X" "-" 2/1 "%02X" "-" 2/1 "%02X" "-" 2/1 "%02X" "-" 6/1 "%02X" "\n"' /dev/random
