#!/bin/bash

##
# Generate a random Facebook app API secret.
#
# This is a random MD5 hash.
#
# Usage:
#
#     random-facebook-app-api-secret
#
# Example:
#
#     $ random-facebook-app-api-secret
#     489bfc1cbe3f7705b306a944917fcc94
#
# See http://facebook.com
#
# By Joel Parker Henderson, joel@joelparkerhenderson.com
#
# License is GPL v2
##

random-md5
