#!/bin/sh
dir="$1"
src="$2"
dst="$3"
test -d "$dir" || echo "The first option must be a directory: $dir" && exit 1
find "$dir" -d | 
while read x do
  rename "s/$src/$dst/" "$x"
  sed -i "s/$src/$dst/g" "$x"
done

