#!/bin/bash
set -euf -o pipefail set -o xtrace
out () { printf %s\\n "$*" ; }

##
# Reset the Ubuntu network wireless driver.
# Credit to Stephen Ostermiller's blog
#
# Running this requires root access.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

driver=`lshw -C network 2>&1 | grep wireless | grep driver | sed 's/.* driver=//; s/ .*//'`
out "driver:$driver"
modprobe -r $driver && modprobe $driver
