#!/bin/bash
set -euf -o pipefail

##
# Remove documentation files.
#
# Typically this is to save space on a server.
#
# https://wiki.ubuntu.com/ReducingDiskFootprint
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

rm -rf /usr/share/doc/*
rm -rf /usr/share/man/*
rm -rf /usr/share/groff/*
rm -rf /usr/share/info/*
rm -rf /var/cache/man/*
