#!/bin/bash
#
# Remove documentation files.
#
# Typically this is to save space on a server.
#
# https://wiki.ubuntu.com/ReducingDiskFootprint
#
set -o nounset
set -o errexit
set -o pipefail

rm -rf /usr/share/doc/*
rm -rf /usr/share/man/*
rm -rf /usr/share/groff/*
rm -rf /usr/share/info/*
rm -rf /var/cache/man/*
