#!/bin/bash
set -euf -o pipefail

##
# Remove translations for languages.
#
# Typically this is to save space on a server.
#
# To remove all except English:
#
#     find /usr/share/locale -mindepth 1 -maxdepth 1 \
#     ! -name 'en' \
#     | xargs rm -r
#
# To remove all except English, Spanish, Chinese:
#
#   find /usr/share/locale -mindepth 1 -maxdepth 1 \
#   ! -name 'en' ! -name 'es*' ! -name 'zh*' \
#   | xargs rm -r
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

find /usr/share/locale -mindepth 1 -maxdepth 1 ! -name 'en' ! xargs rm -r
