#!/bin/bash
set -euf -o pipefail

##
# Remove log rotation files -- DANGER.
#
# Please be certain you don't need
# these log files before you run this.
#
# This removes these kinds of log files from /var/log
#
# Ending in:
#
#   * .gz
#   * .old
#   * .log.[0-9]*
#   * .[0-9]*.log
#
# Any of these logfiles if there's a number suffix:
#
#   * btmp.[0-9]*
#   * mail.err.[0-9]*
#   * syslog.[0-9]*
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

rm -f /var/log/*.{gz,old}
rm -f /var/log/*.log.[0-9]*
rm -f /var/log/**/*.{gz,old}
rm -f /var/log/**/*.log.[0-9]*
rm -f /var/log/**/*.[0-9].log
rm -f /var/log/{btmp,dmesg,mail.err,syslog,wtmp}.[0-9]*

# TODO: preserve the most recent atop file.
rm -f /var/log/atop/atop_[0-9]*
