#!/bin/bash
#
# Remove log rotation files -- DANGER.
#
# Please be certain you don't need
# these log files before you run this.
#
# This removes these kinds of log files from /var/log
#
# Ending in:
#
#   * .gz
#   * .old
#   * .log.[0-9]*
#   * .[0-9]*.log
#
# Any of these logfiles if there's a number suffix:
#
#   * btmp.[0-9]*
#   * mail.err.[0-9]*
#   * syslog.[0-9]*
#
set -o nounset
set -o errexit
set -o pipefail

rm -f /var/log/*.{gz,old}
rm -f /var/log/*.log.[0-9]*
rm -f /var/log/**/*.{gz,old}
rm -f /var/log/**/*.log.[0-9]*
rm -f /var/log/**/*.[0-9].log
rm -f /var/log/{btmp,mail.err,syslog}.[0-9]*
