#!/bin/bash
set -euf -o pipefail

##
# Remove /var/log files that we don't want.
#
# We use this to clean up drive space.
#
# Remove these files:
#
#   * Compressed files, i.e. end in .bz2, .bzip, .gz, .tgz, .zip
#   * Sequence files, e.g. end in ".log.1", "-err.2", etc.
#   * dist-upgrade/*
#   * nagios3/archives/*
#   * samba/log*
#   * unattended-upgrades/unattended-upgrades-dpkg_*.log
#
# Note: we prefer to delete files by using `-exec rm` vs. `-delete`.
# The former is more compatible, the latter is faster.
#
# Tracking:
#
#   * Command: rm-log-files-danger
#   * Version: 1.3.0
#   * Created: 2013-12-09
#   * Updated: 2017-08-29
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

dir=/var/log
find $dir \( -name "*.bz2" -o -name "*.bzip" -o -name "*.gz" -o -name "*.tgz" -o -name "*.zip" -o -regex ".*[-_.]\(log\|err\).[1234567890]+" \) -exec rm {} \;
rm -rf $dir/dist-upgrade/*
rm -rf $dir/log/samba/log*
rm -rf $dir/log/nagios3/archives/*
rm -rf $dir/unattended-upgrades/unattended-upgrades-dpkg_*.log

