#!/bin/bash
set -euf -o pipefail

##
# Remove /var/log files that we don't want.
#
# We use this to clean up drive space.
#
# Remove these files:
#
#   * Compressed files, i.e. end in .bz2, .bzip, .gz, .tgz, .zip
#   * End in .log.123 (any digits)
#   * End in _log.123 (any digits)
#   * dist-upgrade/*
#   * nagios3/archives/*
#   * samba/log*
#
# Tracking:
#
#   * Command: rm-log-files-danger
#   * Version: 1.2.0
#   * Created: 2013-12-09
#   * Updated: 2017-08-29
#   * License: GPL
#   * Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

dir=/var/log
find $dir \( -name "*.bz2" -o -name "*.bzip" -o -name "*.gz" -o -name "*.tgz" -o -name "*.zip" \) -delete
find $dir | grep '\([\._]log\.[[:digit:]]+\)$' | xargs -I{} rm "{}"
rm -rf $dir/dist-upgrade/*
rm -rf $dir/log/samba/log*
rm -rf $dir/log/nagios3/archives/*
