#!/bin/sh
#
# rsync-mirror-merge: rsync-mirror with merge a.k.a. delete all sources.
#
# Syntax:
#
#     rsync-mirror-merge [syntax is the same as rsync]
#
# Example:
#
#     rsync-mirror-merge ~/foo/ ~/bar/
#
# Options set:
#
#   -a, --archive           archive mode; same as -rlptgoD (no -H)
#   -H, --hard-links        preserve hard links
#   -O, --omit-dir-times    omit directories when preserving times
#   -x, --one-file-system   don't cross filesystem boundaries
#   -z, --compress          compress file data during the transfer
#   -i, --itemize-changes   output a change-summary for all updates
#   -u, --update            skip files that are newer on the receiver
#
# Options set by --archive:
#
#   -r, --recursive         recurse into directories
#   -l, --links             copy symlinks as symlinks
#   -p, --perms             preserve permissions
#   -t, --times             preserve times
#   -g, --group             preserve group
#   -o, --owner             preserve owner (super-user only)
#
# Options that are deliberately not set:
#
#   -v, --verbose           increase verbosity
#   --partial               keep partially transferred files
#   --progress              show progress during transfer
#   --copy-links            transform symlink into referent file/dir
#   --safe-links            ignore symlinks that point outside the tree
#
# Reasoning:
#
#   * We like --hard-links even though this is an expensive calculation.
#   * We only use --omit-dir-times because dir times fail on some systems.
#   * We do not use --partial because temp dirs fail on some systems.
#   * We want symlinks as-is, thus no --safe-links, --copy-links, etc.
#
# Known incompatibilities with rsync:
#
#   * each source arg must not start with a dash.
#   * there must be a destination arg.
#
# TODO: a source can start with a dash.
# TODO: one source arg and no destination arg is a noop.
# TODO: add special arg "--" which separates options and sources.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Created: 2015-01-25
# Updated: 2016-01-12
##
set -euf
out () { printf %s\\n "$*" ; }
err () { >&2 printf %s\\n "$*" ; }

rsync -aHuOxzviu "$@"

##
# Remove all sources that are normal directories and normal files.
# This implementation is fine for typical cases but not corner cases.
#
# This implementation steps backwards through the args:
#
#   * Skip the last arg which must be the destination.
#     TODO: one source arg and no destination arg is a noop.
#
#   * If the arg starts with a dash, stop processing.
#     TODO: a source can start with a dash.
#     TODO: add special arg "--" which separates options and sources.
#
#   * If the arg is a normal file or directory, remove it.
#
#   * Otherwise print an error message then break.
##

i=$(($#-1)) 
while [ "$i" -ge 0 ]; do
    x="${!i}"
    case "$x" in
        -*) break ;;
        *) if [ -f "$x" -o -d "$x" ]; then
               rm -fr "$x"
           else
               err "Cannot remove arg because it is not a normal file or directory: $x"
	       break
           fi
    esac
    true $((i=i-1))
done
