#!/bin/sh

##
# Example of using rsync to copy information that we consider public.
#
# This syncs each file that:
#
#   * Is encrypted:
#     * ends with *.gpg
#   * Is a fingerprint:
#     * ends with *.fingerprint, *.fingerprints
#     * named fingerprint, fingerprints
#   * Is public:
#     * in a directory '/public/'
#     * ends with *.pub, *.public
#     * ends with *-public.{pem,txt,url}
##

rsync --archive --hard-links --update --omit-dir-times --one-file-system --compress --verbose --itemize-changes --progress \
  --include '*/' \
  --include '*.gpg' \
  --include '*.fingerprint' \
  --include '*.fingerprints' \
  --include 'fingerprint' \
  --include 'fingerprints' \
  --include '/public/' \
  --include '*.pub' \
  --include '*.public' \
  --include '*-public.pem' \
  --include '*-public.txt' \
  --include '*-public.url' \
  --exclude '*' \
 "$1" "$2"
