#!/bin/sh

##
# Example of using rsync to copy information that we consider public.
#
# This syncs each file that:
#
#   * Is encrypted:
#     * ends with *.gpg
#   * Is a fingerprint:
#     * ends with *.fingerprint, *.fingerprints
#     * named fingerprint, fingerprints
#   * Is public:
#     * in a directory '/public/'
#     * ends with *.pub, *.public
#     * ends with *-public.pem
##

rsync -auvC \
  --include '*/' \
  --include '*.gpg' \
  --include '*.fingerprint' \
  --include '*.fingerprints' \
  --include 'fingerprint' \
  --include 'fingerprints' \
  --include '/public/' \
  --include '*.pub' \
    --include '*.public' \
  --include '*-public.pem' \
  --exclude '*' \
 "$1" "$2"
