#!/bin/bash
set -euf -o pipefail

##
# Our rsync safe syncrhonization, suitable for safe file copies and backups.
#
# Our choices:
#
#   -a, --archive           archive mode; same as -rlptgoD (no -H)
#   -H, --hard-links        preserve hard links
#   -u, --update            skip files that are newer on the receiver
#   -O, --omit-dir-times    omit directories when preserving times
#   -x, --one-file-system   don't cross filesystem boundaries
#   -z, --compress          compress file data during the transfer
#   -v, --verbose           increase verbosity
#   -i, --itemize-changes   output a change-summary for all updates
#   --progress              show progress during transfer
#
# Archive does these:
#
#   -r, --recursive         recurse into directories
#   -l, --links             copy symlinks as symlinks
#   -p, --perms             preserve permissions
#   -t, --times             preserve times
#   -g, --group             preserve group
#   -o, --owner             preserve owner (super-user only)
#
# Notes:
#
#   * We only use --omit-dir-times because dir times fail on some systems.
#   * We do not use --partial because temp dirs fail on some systems.
#   * We want symlinks as-is, thus no --safe-links, --copy-links, etc.
#   * We want --hard-links even though this is an expensive calculation.
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

rsync --archive --hard-links --update --omit-dir-times --one-file-system --compress --verbose --itemize-changes --progress
