#!/usr/bin/env ruby

##
# For each input file name, get the header comments and emit rdoc format.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

set -euf -o pipefail
input_ruby_filename=ARGV[0]

File.exist?(input_ruby_filename) or raise "File #{input_ruby_filename} does not exist"
input=File.new(input_ruby_filename)
began=false

input.each_line{|line|
  break if line=~/^##/ or line=~/^=end/
  next if (line=~/^#!/ or line=~/^# -\*- (encoding|coding): /)
  if line=~/^=begin / then began=true; next; end
  break if !began and (line=~/^$/ and line=~/^\s+/)
  if !began then line.sub!(/^# /,'') end
  puts line
}
