#!/bin/sh
set -euf -o pipefail

##
# Install the `ruby-build` program where we want it.
#
# Compare the `ruby-install-install` script in this same repository.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

cd /opt
test -d ruby-build || sudo git clone --depth 1 https://github.com/sstephenson/ruby-build
cd ruby-build/
sudo git pull
sudo ./install.sh
