#!/bin/bash
#
# Ruby build using our preferred locations:
#
#    /opt/ruby-build is where we put the GitHub repo
#    /opt/ruby/a.b.c-pxxx is where we install Ruby
##

VERSION=$1
cd /opt/ruby-build
git pull
./install.sh
ruby-build $VERSION /opt/ruby/$VERSION
