#!/bin/sh
#
# Use sed to append a newline to the last line of stream, if it's missing.
#
#  * '$a\' says "match the last line of the file, and add nothing to it."
#
#  * Implicitly, sed appends a newline to every line it processes,
#    such as this $ line, if the newline is not already there.

sed '$a\'
