#!/bin/sh
#
# Change smart characters into simple characters.
#
# Items:
#
#   * curly quote => """
#   * curly apostrophe => "'"
#   * n-dash => "-"
#   * m-dash => " -- "
#
# Version: 1.7.0
# Created: 2011-08-18
# Updated: 2015-01-25
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
sed "s/[”“]/\"/g; s/’/'/g; s/–/-/g; s/—/ -- /g"
