#!/bin/sh
#
# sed script to print the VERSION string from a text file.
#
# Version: 1.3.0
# Created: 2011-10-30
# Updated: 2015-01-25
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
sed 's/^ *VERSION[^0-9]*//; s/[^0-9A-Za-z_\.-].*//'
