#!/bin/sh

##
# Change smart characters into simple characters:
#   * curly quote => """
#   * curly apostrophe => "'"
#   * n-dash => "-"
#   * m-dash => " -- "
##

sed "s/[”“]/\"/g; s/’/'/g; s/–/-/g; s/—/ -- /g"
