#!/bin/bash
set -euf -o pipefail

##
# Delete all leading blank lines at top of file.
# From http://sed.sourceforge.net/sed1line.txt
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

sed '/./,$!d'
