#!/bin/sh
#
# sed script to join each line that starts with a blank.
#
# If a line begins with a blank, then append it to the
# previous line and replace leading blanks with a single space.
#
# From http://sed.sourceforge.net/sed1line.txt
#
# ## Explanation
#
# The command works like this:
#
#     :a
#     |---> create label
#      |--> label name `a`
#
#     $!N
#     |----> if not the last line
#       |--> then append the next line
#
#     s/\n[[:blank:]]*/ /
#     |-------------------> search for
#       |-----------------> newline
#         |---------------> blank whitespace
#                    |----> match 0 or more
#                     |---> replace with
#                      |--> space
#
#     ta
#     |---> if replace is true
#      |--> go to label `a`
#
#     P;D
#     |----> print
#       |--> delete
#
# ## Tracking
#
# Command: sed-join-when-next-line-starts-with-blanks
# Version: 1.2.0
# Created: 2013-08-19
# Updated: 2017-01-28
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
sed -e :a -e '$!N; s/\n[[:blank:]]\+/ /; ta' -e 'P;D'
