#!/bin/bash
set -euf -o pipefail

##
# Delete all trailing blank lines.
# From http://sed.sourceforge.net/sed1line.txt
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

sed -e :a -e '/^\n*$/{$d;N;ba' -e '}'
