#!/bin/bash
set -euf -o pipefail

##
# sed script to join lines that end with equal signs.
#
# If a line begins with an equal sign, append it to the
# previous line and replace the "=" with a single space.
#
# From http://sed.sourceforge.net/sed1line.txt
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

sed -e :a -e '$!N;s/\n=/ /;ta' -e 'P;D'
