#!/bin/sh
#
# Use sed to find the end-of-stream and append a newline character
# as needed, i.e. if there is not an existing newline character.
#
# How this works:
#
#  * '$a\' matches the last line of the file.
#
#  * Implicitly, sed appends a newline to every line it processes,
#    such as this $ line, if the newline is not already there.
#
sed '$a\'
