#!/bin/sh
#
# sed script to join each line that ends with a backslash.
#
# If a line ends with a backslash, then join it to the next line.
#
# From http://sed.sourceforge.net/sed1line.txt
#
# ## Explanation
#
# The command works like this:
#
#     :a
#     |---> create label
#      |--> label name `a`
#
#     /\\$/N
#     |-------> match
#      |------> backslash
#        |----> end of line
#          |--> next
#
#     s/\\\n//
#     |---------> search for
#       |-------> backslash and newline
#           |---> replace with
#            |--> nothing
#
#     ta
#     |---> if replace is true
#      |--> go to label `a`
#
# ## Tracking
#
# Command: sed-join-when-this-line-ends-with-backslash
# Version: 1.2.0
# Created: 2013-08-19
# Updated: 2017-01-28
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
sed -e :a -e '/\\$/N; s/\\\n//; ta'
