#!/bin/sh
set -euf -o pipefail

##
# Delete trailing space characters, such as spaces and tabs.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2019-08-12
##

sed 's/[[:space:]]\{1,\}$//'
