#!/bin/bash
set -euf -o pipefail

##
# Delete most HTML tags.
#
# This accommodates multiple-line tags.
#
# From http://sed.sourceforge.net/sed1line.txt
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

sed -e :a -e 's/<[^>]*>//g;/</N;//ba'
