#!/bin/bash
set -euf -o pipefail

##
# Delete duplicate, nonconsecutive lines from a file.
#
# Beware not to overflow the buffer size of the hold space.
# From http://sed.sourceforge.net/sed1line.txt
#
# Maintainer: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

sed -n 'G; s/\n/&&/; /^\([ -~]*\n\).*\n\1/d; s/\n//; h; P'
