#!/bin/sh

##
# Delete duplicate, nonconsecutive lines from a file. 
# Beware not to overflow the buffer size of the hold space.
# From http://sed.sourceforge.net/sed1line.txt
##

sed -n 'G; s/\n/&&/; /^\([ -~]*\n\).*\n\1/d; s/\n//; h; P'