#!/usr/bin/env python3

##
# Script to show GitHub API issues data.
#
# Syntax:
#
#     sixarm-github-api-issues-data
# 
# Example:
#
#     $ TOKEN=fe7f2bf4057de85eb638dc7356047b0e31d24a4b sixarm-github-api-issues-data
#
# Documentation:
#
#    * https://pygithub.readthedocs.io/en/latest/introduction.html
#
#
# ## Dependencies
#
# This script uses `pygithub`.
#
# Install:
#
#     $ pip install pygithub
#
#
# ## Troubleshooting
#
# If you get the error message:
#
#.    ModuleNotFoundError: No module named 'github'
#
# Then try installing using a specific python instance:
#
#     $ python3 -m pip install --upgrade pip
#     $ python3 -m pip install pygithub
#
# ## GitHub Enterprise
#
# If you use Github Enterprise with custom hostname,
# then you need to adjust this script by doing:
#
#     g = Github(base_url="https://{hostname}/api/v3", login_or_token="token")
#
##
import os
import sys

token = os.environ['TOKEN']
print(token)

owner_repo = sys.argv[1]
print (f"owner/repo:{owner_repo}")

from github import Github

g = Github(os.environ['TOKEN'])

# Example: get repos
#
#for repo in g.get_user().get_repos():
#    print(repo.name)


repo = g.get_repo(owner_repo)
print(repo.name)

for issue in repo.get_issues():
	print(f"title:{issue.title}")
	#print(issue.body)
	labels = issue.labels
	for label in labels:
		print(f"label:{label.name} color:{label.color}")



