#!/bin/bash
set -euf -o pipefail

##
# Sort command-line input by rank.
#
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

sort | uniq -c | sort -g
