#!/bin/sh
# Find any mail messages in my inbox (~/Maildir/cur) that contain a given phrase,
# and move these messages to my spambox (~/Maildir/spam) for my review or deletion.
find ~/Maildir/cur | xargs grep -l "$1" | xargs -I{} mv "{}" ~/Maildir/spam/
