#!/bin/bash
set -euf -o pipefail

##
# Split a file by lines evenly to <num> new output files.
# This uses the split command.
#
# Syntax:
#
#    split-lines-evenly <filename> <number-of-output-files>
#
# Example:
#
#    split-lines-evenly hello.txt 3
#    #=>
#    hello.txt.0
#    hello.txt.1
#    hello.txt.2
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

input_file=$1  # e.g. "hello.txt"
output_pieces=$2  # e.g. "3" to split the file into three output files
shift 2  # the rest are passed as-is to the split command

input_file_line_count=($(wc -l $input_file)+0)
((lines_per_file=(input_file_line_count + output_pieces - 1) / output_pieces))

split --numeric-suffixes --suffix-length=1 --lines=$lines_per_file $@ $input_file $input_file.
