#!/bin/bash
set -euf -o pipefail

##
# SSH script to generate our typical key:
#
#   * rsa algorithm because it's the widest used.
#   * 4096 bytes of strength; default would be 2048.
#   * append a comment that is the user's email address.
#   * set the file name to "<email>=<fingerprintx>=id_rsa"
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

email=$1
temp=$(mktemp -t `basename $0`)
echo "temp:$temp"
echo 'y' | ssh-keygen -t rsa -b 4096 -C "$email" -f "$temp"
fingerprintx=$(ssh-keygen -lf "$temp.pub" | awk '{print $2}' | sed 's/://g')
file="$email=$fingerprintx=id_rsa"
mv "$temp" "$file"
mv "$temp.pub" "$file.pub"
echo "$file"
echo "$file.pub"
