#!/bin/bash
set -euf -o pipefail

##
# Set the correct directory permissions of the current user's ~/.ssh directory.
# SSH security requires restricted permissions, and will block without them.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

unset CDPATH
cd ~/.ssh && chmod 700 . && chmod 600 *
