#!/bin/bash
#
# To get ssh key fingerprints from a server, 
# and print them in a human readable format,
# we use `ssh-keyscan` and `ssh-kegen`.
#
# Example:
#
#    ssh-keyscan-keygen 1.2.3.4
#    2048 02:fc:a5:ff:97:dd:41:63:bb:88:8b:29:4e:75:23:ed 1.2.3.4 (RSA)
#    256 ea:bc:4d:5f:ae:00:48:75:45:ba:97:43:fe:e1:a3:e9 1.2.3.4 (ECDSA)
#
# Credit: http://stackoverflow.com/questions/13791219/ssh-fingerprint-verification-for-amazon-aws-ec2-server-with-ecdsa
#
host="$1"
file="ssh-keyscan-$1.tmp"
ssh-keyscan "$1" > "$file"
ssh-keygen -l -f "$file"
rm "$file"
