#!/bin/sh
set -euf -o pipefail

##
# Get the SSH fingerprint of known host.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

ssh-keygen -l -F $1
