#!/bin/sh
# Set the correct directory permissions of the current user's ~/.ssh directory.
# SSH security requires restricted permissions, and will block without them.

cd ~/.ssh && chmod 700 . && chmod 600 *
