#!/bin/bash
set -euf -o pipefail

##
# SSH script to print a server's ssh host public key fingerprints.
#
# Typical locations for fingerprints:
#
#   * Debian: /etc/ssh/ssh_host*.pub
#   * OSX: /etc/ssh_host*.pub
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

find -L /etc -name 'ssh_host*.pub' | xargs -I{} ssh-keygen -l -f {}
