#!/bin/bash
set -euf -o pipefail

##
# SSH script to copy a pub id file to a remote server into your authorized_keys.
#
# Syntax:
#   ssh-copy-id-util <pub file> <ssh login>
#
# Example:
#   ssh-copy-id-util ~/.ssh/id_rsa.pub me@foo.bar.com
#   => cat ~/.ssh/id_rsa.pub | ssh me@foo.bar.com "cat >> ~/.ssh/authorized_keys"
#
# This script is a substitude for ssh-copy-id (use it if you have it).
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

cat ~/.ssh/id_dsa.pub | ssh me@remotebox "cat >> ~/.ssh/authorized_keys"
