#!/bin/sh
set -euf -o pipefail

##
# SSH script to generate our typical key:
#
#   * RSA algorithm because it's the widest used.
#   * 4096 bytes of strength; default would be 2048.
#   * append a comment that is the user's email address.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

ssh-keygen -t rsa -b 4096 -C "$email"
