#!/bin/sh
#
# Run tar using bzip2 compression.
#
# Example:
#
#     $ tar-bzip2 mydir
#     $ ls
#     mydir.bz
#
# Version: 1.5.0
# Created: 2012-02-17
# Updated: 2016-01-15
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
##
set -euf
tar --use-compress-program /usr/local/bin/bzip2
