#!/bin/bash
set -euf -o pipefail

##
# Set an iTerm tab title
#
# Example:
#
#   term-tab-title hello world
#
# From http://blog.locut.us/2009/10/30/simple-bash-script-to-name-a-tab-in-iterm/
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

echo -ne "\033];"$@"\007"
