#!/bin/bash
set -euf -o pipefail

##
# Use tmux to a shared session
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

tmux -S /tmp/tmux-shared "$@"
