#!/bin/bash
set -euf -o pipefail

##
# Use tmux to send keys to a new window.
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

window=$1
shift
tmux new-window -n "$window"
tmux send-keys -t "$window" "$*"
