#!/bin/sh
#
# Use tmux to send keys to a new window.
#
# Version: 1.2.0
# Created: 2013-09-09
# Updated: 2015-01-25
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
window=$1
shift
tmux new-window -n "$window"
tmux send-keys -t "$window" "$*"
