#!/bin/bash
set -euf -o pipefail

##
# Syntax: tmux-attach-session-or-new-session [session-name]
#
# If the tmux session name _session-name_ exists,
# then attach to it, otherwise create it.
#
# Example:
#
#    tmux-attach-session-or-new-session foo
#    #=> creates new session name "foo"
#
# The _session-name_ defaults to the basename of the pwd.
#
# Example:
#
#    cd /a/b/c/foo
#    tmux-attach-session-or-new-session
#    #=> creates new session name "foo"
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

session=${1-`basename \`pwd\``}
tmux has-session -s "$session" &&
tmux attach-session -t "$session" ||
tmux new-session -s "$session"
