#!/bin/bash
#
# Launch tmux suitable for Rails development.
#
# Syntax:
#
#     tmux-rails [session-name]
#
# This script attaches to session-name (and creates it if needed).
#
# The _session-name_ defaults to the basename of the pwd.
#
#
# This launches these windows with these commands:
#
#   * !1:edit = $EDITOR
#   * @2:test = bundle exec bin/rake test
#   * #3:log = cd log && tail -f log/development.log
#   * $4:console = rails console
#   * %5:db = rails db
#   * ^6:deploy = rake deploy
#   * &7:server = rails server
#
set -o nounset
set -o errexit
set -o pipefail

## This section is from tmux-use-session
session=${1-`basename \`pwd\``}
#tmux has-session -s "$session" &&
#tmux attach-session -t "$session" ||
#tmux new-session -s "$session"

rake="bundle exec bin/rake"
rails="bundle exec bin/rails"

function tmux-new-window-with-keys(){
  session=$1
  window=$2
  keys=$3
  tmux new-window -n "$window" -t "$session"
  tmux send-keys -t "$session:$window" "$keys" C-m
}

tmux-new-window-with-keys "$session" "edit" "$EDITOR"
tmux-new-window-with-keys "$session" "test" "$rake test"
tmux-new-window-with-keys "$session" "console" "$rails console"
tmux-new-window-with-keys "$session" "log" "cd log && tail -f development.log"
tmux-new-window-with-keys "$session" "db" "$rails db" C-m
tmux-new-window-with-keys "$session" "deploy" ""
tmux-new-window-with-keys "$session" "server" "$rails server"
tmux -q select-window 'edit'
