#!/bin/bash
#
# Find TODO lines in files.
#
# This script searches for all of these:
#
#    #TODO
#    #FIX
#    #FIXME
#    #OPTIMIZE
#    #DEPRECATE
#    #REFACTOR
#    #DELETE
#    #AUDIT
#    #DANGER
#    #WTF
#
# Syntax:
#
#   todos [options that are passed along to _ag_]
#
# Example:
#
#   todos
#
# Example to show two lines of context before and after:
#
#   todos -C 2
#
# The hash can have an optional space after it;
# this is so the search finds code comments too.
#
# If you're writing TODO lines, please use no space
# because this is more like our preferred tag style.
#
# The search the _ag_ command a.k.a. "the silver searcher".
# The _ag_ command is a lot like the _grep_ command.
# See https://github.com/ggreer/the_silver_searcher
#
# The output will show the file names, line numbers,
# and colorize the match hits if you have color set up.
#
# The search is recursive by default, and skips some directories
# such as ".git", and skips some files such as binary blogs.
#
# You can tune the behavior as you like by using any
# of the _ag_ options; this script passes the options along.
#
# If you prefer using the _grep_ command, or _ack_ command,
# then you can easily edit this script to your taste.
#
# Version: 1.5.0
# Created: 2014-02-12
# Updated: 2015-01-25
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
ag "# *(TODO|FIX|FIXME|OPTIMIZE|DEPRECATE|REFACTOR|DELETE|AUDIT|DANGER|WTF)\b" "$@"
