#!/bin/sh
#
# Set trackpoint speed and sensitivity to fastest settings.
# This also turns on the trackpoint option for press-to-select.

for i in 1 2 3 
do
 dir=/sys/devices/platform/i8042/serio1/serio$i
 if [ -d $dir ]; then
  sudo echo -n 255 > $dir/speed
  sudo echo -n 255 > $dir/sensitivity
  sudo echo -n 1 > $dir/press_to_select
 fi
done
