#!/bin/sh
#
# Show all the X files for which there doesn't exist a Y file.
#
# To show all the .c files that don't have a corresponding .o file:
#
#   twinless .c .o
#
# Version: 1.4.0
# Created: 2014-05-26
# Updated: 2015-01-25
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
##
set -euf
print *$1(e_'[[ ! -e $REPLY:r$2 ]]'_)
