#!/bin/bash
set -euf -o pipefail

##
# Show me all the X files for which there doesn't exist a Y file.
#
# To show all the .c files that don't have a corresponding .o file:
#
#   twinless .c .o
#
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

print *$1(e_'[[ ! -e $REPLY:r$2 ]]'_)
