#!/bin/bash
set -euf -o pipefail

##
# Ubuntu script to turn off the login sound.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

sudo -u gdm gconftool-2 --set /desktop/gnome/sound/event_sounds --type bool false
