#!/bin/bash
#
# Unmount a Nexus phone.
#
# Version: 1.2.0
# Created: 2014-05-26
# Updated: 2015-01-25
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
##
set -euf -o pipefail
out () { printf %s\\n "$*" ; }

dir=/media/nexus4
test -e $dir && sudo umount $dir
if [ -e $dir ]; then
  out "Path still exists: $dir"
  out "lsof -w $dir"
  lsof -w $dir
  out
  out "fuser $dir"
  fuser $dir
fi
