#!/bin/bash
set -euf -o pipefail
out () { printf %s\\n "$*" ; }

##
# Unmount a Nexus 4 phone.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

dir=/media/nexus4
test -e $dir && sudo umount $dir
if [ -e $dir ]; then
  out "Path still exists: $dir"
  out "lsof -w $dir"
  lsof -w $dir
  out
  out "fuser $dir"
  fuser $dir
fi
