#!/bin/bash
set -euf -o pipefail

##
# Unmount a Nexus 4 phone.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

dir=/media/nexus4
test -e $dir && sudo umount $dir
if [ -e $dir ]; then
  echo "Path still exists: $dir"
  echo "lsof -w $dir"
  lsof -w $dir
  echo
  echo "fuser $dir"
  fuser $dir
fi
