#!/bin/sh
#
# Print the lines that are in any of the inputs.
#
# Syntax:
#
#     union <input> ...
#
# Examples:
#
#     union a.txt b.txt
#     => lines that are in either of the files.
#
#     union a.txt b.txt c.txt
#     => lines that are in any of the files.
#
# ## Specifics
#
# The order does not matter.
#
# ## Related
#
# These commands are related:
#
#   * `union`: print lines in (A union B)
#   * `intersect`: print lines in (A intersect B)
#   * `except`: print lines in (A except B) a.k.a. (A - B)
#   * `extra` : print lines in (A extra B) a.k.a. (B - A)
#
# ## Notes
#
# In set theory, this is (A union B).
#
# This command aims to be fast, not to sort.
#
# This command is currently implemented using `awk`.
#
# ## Tracking
#
# Program: union
# Version: 2.0.2
# Created: 2017-01-30
# Updated: 2017-01-30
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -eu
awk '!seen[$0] {print} {seen[$0]=1}' "$@"
