#!/bin/bash
#
# Show diagnostic details about the linux version.
# I.e. tell me about the current operating system.
#
set -o nounset
set -o errexit
set -o pipefail

if $(command -v uname >/dev/null 2>&1); then
    echo 'uname -a'
    uname -a
    echo
fi

for file in /etc/redhat-release /proc/version /etc/issue.net
do
  if [[ -e $file ]]
  then
    echo ''
    echo "cat $file"
    cat $file
  fi;
done

if $(command -v lsb_release >/dev/null 2>&1); then
    echo 'lsb_release -a'
    lsb_release -a
    echo
fi

if $(command -v sw_vers >/dev/null 2>&1); then
    echo 'sw_vers'
    sw_vers
    echo
fi
