#!/bin/bash
#
# Show diagnostic details about the linux version.
# I.e. tell me about the current operating system.
#
set -o nounset
set -o errexit
set -o pipefail

# Unix uses `uname` to print info like this:
#
# Linux:
#
#     Linux hostname 2.6.35.4-rscloud #8 SMP
#     Mon Sep 20 15:54:33 UTC 2010
#     x86_64 GNU/Linux
#
# OSX:
#
#     Darwin hostname 14.0.0
#     Darwin Kernel Version 14.0.0:
#     Fri Sep 19 00:26:44 PDT 2014;
#     root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
#
if $(command -v uname >/dev/null 2>&1); then
    echo 'uname -a'
    uname -a
    echo
fi

for file in /etc/redhat-release /proc/version /etc/issue.net
do
  if [[ -e $file ]]
  then
    echo ''
    echo "cat $file"
    cat $file
  fi;
done

if $(command -v lsb_release >/dev/null 2>&1); then
    echo 'lsb_release -a'
    lsb_release -a
    echo
fi

# OSX uses `sw_vers` to print info like this:
#
#     $ sw_vers
#     ProductName:Mac OS X
#     ProductVersion:10.10
#     BuildVersion:14A389
#
if $(command -v sw_vers >/dev/null 2>&1); then
    echo 'sw_vers'
    sw_vers
    echo
fi
