#!/bin/zsh
set -euf -o pipefail

##
# Run update commands for everything we use on all platforms.
#
# Heuristics:
#
#   1. Update OS and packages, such as `apt`, `softwareupdate`, `brew`, etc.
#   2. Update language application packages: `gem`, `pip`, `npm`, `motion`, etc.
#   3. Update our local git repositories: `/opt`, `~/git`, etc.
#
# More to come. We welcome patches, pull requests, and ideas.
#
# Author: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-06-01
##

update-apt
update-osx
update-brew
update-apm
update-gem
update-pip
update-npm
update-motion
update-repos
