#!/bin/bash
set -euf -o pipefail

##
# uri-scheme
#
# Output the URI scheme parts.
#
# Syntax:
#
#    <uri> | uri-scheme [selector] ...
#
# Example:
#
#   $ echo "http://www.example.com:80" | uri-scheme
#   name: http
#   authority: www.example.com:80
#   host: www.example.com
#   port: 80
#
# Example with one selector:
#
#   $ echo "http://www.example.com:80" | uri-scheme host
#   www.example.com
#
# Example with multiple selectors:
#
#   $ echo "http://www.example.com:80" | uri-scheme port host
#   80 www.example.com
#
# See http://en.wikipedia.org/wiki/URI_scheme
#
# Scheme parts:
#
#   * uri: "http://@www.example.com:80/a/b/c.html?d=e&f=g#hi"
#   * name: "http"
#   * hierarchical: "//user:pass@www.example.com:80/a/b/c.html?d=e&f=g#hi"
#     * authority: "user:pass@www.example.com:80"
#       * userinfo: "user:pass"
#         * username: "user"
#         * password: "secret"
#       * host: "www.example.com"
#       * port: "80"
#     * path: "/a/b/c.html"
#       * file: "c.html"
#   * query: "d=e&f=g"
#   * fragment: "hi"
#
# Example:
#
#    $ echo "http://user:pass@www.example.com:80/a/b/c.html?d=e&f=g#hi" | uri-scheme
#    uri: http://user:pass@www.example.com:80/a/b/c?d=e#fg
#    scheme: http
#    hierarchical: //user:pass@www.example.com:80/a/b/c
#    query: d=e
#    fragment: fg
#    authority: user:pass@www.example.com:80
#    userinfo: user:pass
#    host: www.example.com
#    port: 80
#    path: /a/b/c
#
# Caution: this current implementation is sufficient for our internal needs;
# it is generally accurate for typical URIs, but is not standards-compliant.
#
# TODO: improve parsing; improve standards; improve speed.
#
##

read uri
echo "uri:$uri"

read name hierarchical query fragment < <(echo "$uri" | sed -n -E 's~^(([[:alpha:]][[:alnum:]\.\+\-]*):)([^\?\#]*)(\?([^#]*))?(#(.*?))?$~\2 \3 \5 \7~p')
echo "name:$name"
echo "hierarchical:$hierarchical"

if [[ "$hierarchical" =~ ^// ]]; then
  read authority path < <(echo "$hierarchical" | sed -n -E 's~^(//)?([^/]*)~\2 ~p')
else
  path="${hierarchical#//}"
fi

if [ -n "$authority" ]; then
    userinfo=$(echo "$authority" | sed -n -E 's~^(.+)@.*$~\1~p')
    host=$(echo "$authority" | sed -n -E 's~^(.*@)?([^:]*)(:.*)?$~\2~p')
    port=$(echo "$authority" | sed -n -E 's~.*:([[:digit:]]+)$~\1~p')
fi

echo "authority:$authority"

if [ -n "$userinfo" ]; then
    read username password < <(echo "$userinfo" | sed -n -E 's~^(.*):(.*)~\1 \2~p')
fi

if [ -n "$path" ]; then
    read file < <(echo "$path" | sed -n -E 's~^(.*/)(.*)$~\2~p')
fi

if [ $# -eq 0 ]; then
    if [ -n "${uri:-}" ]; then echo "uri: $uri"; fi
    if [ -n "${name:-}" ]; then echo "name: $name"; fi
    if [ -n "${hierarchical:-}" ]; then echo "hierarchical: $hierarchical"; fi
    if [ -n "${authority:-}" ]; then echo "authority: $authority"; fi
    if [ -n "${userinfo:-}" ]; then echo "userinfo: $userinfo"; fi
    if [ -n "${username:-}" ]; then echo "username: $username"; fi
    if [ -n "${password:-}" ]; then echo "password: $password"; fi
    if [ -n "${host:-}" ]; then echo "host: $host"; fi
    if [ -n "${port:-}" ]; then echo "port: <$port>"; fi
    if [ -n "${path:-}" ]; then echo "path: $path"; fi
    if [ -n "${file:-}" ]; then echo "file: $file"; fi
    if [ -n "${query:-}" ]; then echo "query: $query"; fi
    if [ -n "${fragment:-}" ]; then echo "fragment: $fragment"; fi
else
    s=""
    for selector in "$@"; do
        case "$selector" in
            uri )
                s="$s $uri"
                ;;
            name )
                s="$s $name"
                ;;
            hierarchical )
                s="$s $hierarchical"
                ;;
            authority )
                s="$s $authority"
                ;;
            userinfo )
                s="$s $userinfo"
                ;;
            username )
                s="$s $username"
                ;;
            password )
                s="$s $password"
                ;;
            host )
                s="$s $host"
                ;;
            port )
                s="$s $port"
                ;;
            path )
                s="$s $path"
                ;;
            file )
                s="$s $file"
                ;;
            query )
                s="$s $query"
                ;;
            fragment )
                s="$s $fragment"
                ;;
        esac
    done
    echo "${s# }"
fi
