#!/usr/bin/env python3

##
# URI to meta property content
#
# Example:
#
#    $ uri-to-meta-property-content http://example.com/ og:title og:description
#    My Title
#    My Description
##

import argparse
import requests
import json
from bs4 import BeautifulSoup

parser = argparse.ArgumentParser(description='Fetch a URI then print Open Graph content')
parser.add_argument('uri', help='URI to fetch then parse')
parser.add_argument('properties', nargs='+', help='list of HTML meta tag properties to find')
args = parser.parse_args()

headers = {
    'Content-Type': 'text/html',
    'User-Agent': 'Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)',
}

response = requests.get(args.uri, headers=headers)
html = response.text
soup = BeautifulSoup(html, 'html.parser')

out = {}
for property in args.properties:
    content = soup.find(attrs={"property" : property}).get('content')
    out[property] = content
print(json.dumps(out, indent=4))
