#!/bin/sh
set -euf -o pipefail

##
# URI script to decode text, for example a CGI query string.
#
# This implementation works by using perl and the URI::Escape module.
#
# Command: uri-decode-by-perl
# Version: 1.5.0
# Created: 2010-05-20
# Updated: 2016-09-12
# License: BSD, GPL, MIT
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

perl -MURI::Escape -lne 'print uri_unescape($_)'
