#!/usr/bin/env python3

import argparse
import requests
from bs4 import BeautifulSoup

parser = argparse.ArgumentParser(description='Fetch a URI then print Open Graph content')
parser.add_argument('uri', help='the web link to fetch')
args = parser.parse_args()

uri = args.uri
print(uri)
headers = {'Content-Type': 'text/html',}
response = requests.get(uri, headers=headers)
html = response.text

soup = BeautifulSoup(html, 'html.parser')
og_url = soup.find(attrs={"property" : "og:url"}).get('content')
og_image = soup.find(attrs={"property" : "og:image"}).get('content')
og_title = soup.find(attrs={"property" : "og:title"}).get('content')
og_description = soup.find(attrs={"property" : "og:description"}).get('content')

print(og_url)
print(og_image)
print(og_title)
print(og_description)
