#!/bin/bash
set -euf -o pipefail

##
# URI script to escape text, for example a CGI query string.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

perl -MURI::Escape -lne 'print uri_escape($_)'
