#!/bin/sh
set -euf -o pipefail

##
# Change to another user by running sudo su -
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

sudo su - $@
