#!/bin/bash
#
# Search-and-replace the VERSION number in a text file.
#
set -o nounset
set -o errexit
set -o pipefail

version_file=$1
old_version=`cat $version_file | sed 's/^ *VERSION[^0-9]*//; s/[^0-9A-Za-z_\.-].*//'`
echo "Old version: $old_version"
read -p "New version: " new_version
sed -i "s/$old_version/$new_version/g" $version_file
