#!/bin/bash
set -euf -o pipefail
out () { printf %s\\n "$*" ; }

##
# Search-and-replace the VERSION number in a text file.
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-01-25
##

version_file=$1
old_version=`cat $version_file | sed 's/^ *VERSION[^0-9]*//; s/[^0-9A-Za-z_\.-].*//'`
out "Old version: $old_version"
read -p "New version: " new_version
sed -i "s/$old_version/$new_version/g" $version_file
