#!/bin/sh
set -euf
help(){
cat <<EOF

$0

Parse the FTP transfer log to date summary statitics.

Example to count transfers of the file name `hello.txt`:

    cat /var/log/proftpd/xferlog |
    xferlog-stats-date-summary

Version: 1.0.0
Created: 2016-01-14
Updated: 2016-01-15
License: GPL
Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)

EOF
}

nice cat xferlog | nice awk '{ date=$2 " " $3; date_count[date]++; date_bytes[date]+=$8 } END { for (date in date_count) print date " " date_count[date] " " date_bytes[date] }'
