#!/usr/bin/env ruby

##
# yaml-to-json converts text from YAML to JSON.
#
# Example:
#
#     cat example.yaml | yaml-to-json > example.json
#
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
# License: GPL
# Updated: 2015-03-24
##

require 'yaml'
require 'json'
text = ARGF.read
yaml = YAML::load(text)
json = JSON.pretty_generate(yaml)
puts json
