#!/bin/sh
set -euf

##
# Run yardoc on all our lib files.
#
# Version: 1.0.0
# Created: 2010-05-20
# Updated: 2016-01-15
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##

yardoc lib/**/*.rb
