#!/bin/bash
#
# YouTube script to get the "watch" title.
#
set -o nounset
set -o errexit
set -o pipefail

grep '/watch?v=.* title=' | sed 's#.*\(/watch?v=[^"]*\).* title="\([^"]*\).*#http://www.youtube.com\1 \2#'
