#!/bin/bash
#
# YouTube script to scrape the "MySmartHands" American Sign Language videos.
#
# See http://www.youtube.com/user/SmartHandsCA
#
# This script scrapes the youtube sidebar list of videos,
# chooses each video with a title havin "ASL sign for",
# a list of links to videos sorted by title.
#
set -o nounset
set -o errexit
set -o pipefail

cat videos.html | youtube-scrape-watch-title | grep ' - ASL sign for ' | sed 's# - ASL sign for .*##' | sort -k2
