#!/bin/sh
#
# YouTube script to get the "watch" title.
#
# Version: 1.0.0
# Created: 2010-10-15
# Updated: 2016-01-15
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
grep '/watch?v=.* title=' | sed 's#.*\(/watch?v=[^"]*\).* title="\([^"]*\).*#http://www.youtube.com\1 \2#'
